import type { FastifyInstance } from 'fastify'
import { db } from '../db/index.js'
import { rawRows } from '../db/raw-rows.js'
import { requireAdmin } from '../middleware/authenticate.js'
import { logActivity } from '../services/activity.js'
import { getFields } from '../services/collections.js'
import { createOne } from '../services/items.js'

/**
 * Test data generator (#512) — dev affordance for empty/new collections.
 *
 * POST /test-data/:collection { count?, respect_required?, allow_nonempty?, seed? }
 *   requireAdmin · business collections only · REFUSES non-empty collections
 *   unless allow_nonempty — generated rows in a live table are a mess nobody
 *   asked for. Rows go through createOne per row, so hooks, field rules,
 *   validation and activity logging all apply (a row a real caller couldn't
 *   save is reported as a per-row error, never silently forced in).
 *
 * Deterministic when `seed` is passed (mulberry32) — the same seed yields the
 * same rows, which makes generated fixtures reproducible across environments.
 *
 * Orchestrator wires it in routes/index.ts:
 *   import { testDataRoutes } from './test-data.js'
 *   await app.register(testDataRoutes)
 */

const TABLE_NAME_RE = /^[A-Za-z_][A-Za-z0-9_]*$/
const MAX_COUNT = 100

const FIRST_NAMES = ['Ava', 'Liam', 'Maya', 'Noah', 'Zoe', 'Ethan', 'Ruby', 'Owen', 'Isla', 'Levi', 'Nora', 'Silas']
const LAST_NAMES = ['Hartwell', 'Okafor', 'Lindqvist', 'Moreau', 'Takeda', 'Alvarez', 'Whitfield', 'Novak', 'Iverson', 'Castellano']
const CITIES = ['Portland', 'Denver', 'Austin', 'Raleigh', 'Madison', 'Boise', 'Savannah', 'Tacoma', 'Provo', 'Albany']
const STATES = ['OR', 'CO', 'TX', 'NC', 'WI', 'ID', 'GA', 'WA', 'UT', 'NY']
const STREETS = ['Maple Ave', 'Cedar St', 'Oakridge Dr', 'Willow Ln', 'Summit Blvd', 'Harbor Rd', 'Foxglove Ct', 'Juniper Way']
const COMPANIES = ['Northwind Labs', 'Bluepeak Systems', 'Cascade Works', 'Ironvale Group', 'Halcyon Partners', 'Stonebrook Co']
const WORDS = ['alpha', 'harbor', 'summit', 'cobalt', 'meridian', 'lattice', 'quartz', 'beacon', 'delta', 'orchid', 'vertex', 'aurora']
const SENTENCES = [
  'Generated sample record for testing and demos.',
  'Placeholder content — replace with real data before launch.',
  'Auto-generated by the test data tool; safe to delete.',
  'Example row used to exercise layouts, rules and workflows.'
]

/** Deterministic PRNG — same seed, same sequence, every platform. */
function mulberry32(seed: number): () => number {
  let a = seed >>> 0
  return () => {
    a |= 0
    a = (a + 0x6d2b79f5) | 0
    let t = Math.imul(a ^ (a >>> 15), 1 | a)
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296
  }
}

type Rng = () => number
const pick = <T>(rng: Rng, arr: T[]): T => arr[Math.floor(rng() * arr.length)]
const int = (rng: Rng, min: number, max: number) => Math.floor(rng() * (max - min + 1)) + min

function fakeHex(rng: Rng, len: number): string {
  let out = ''
  for (let i = 0; i < len; i++) out += '0123456789abcdef'[Math.floor(rng() * 16)]
  return out
}

function fakeDate(rng: Rng): string {
  const d = new Date(Date.now() + (rng() * 180 - 90) * 86_400_000)
  return d.toISOString()
}

type FieldMeta = {
  field: string
  type?: string | null
  interface?: string | null
  options?: string | null
  required?: boolean | number | null
  computed_type?: string | null
  computed_formula?: string | null
}

function parseChoices(options: unknown): string[] {
  if (!options) return []
  let parsed: unknown = options
  if (typeof options === 'string') {
    try {
      parsed = JSON.parse(options)
    } catch {
      return []
    }
  }
  const list = Array.isArray(parsed)
    ? parsed
    : Array.isArray((parsed as { choices?: unknown[] })?.choices)
      ? (parsed as { choices: unknown[] }).choices
      : []
  return list
    .map((c) => (c && typeof c === 'object' ? String((c as { value?: unknown }).value ?? '') : ''))
    .filter(Boolean)
}

function hasAutoId(options: unknown): boolean {
  if (typeof options !== 'string') return false
  try {
    const p = JSON.parse(options) as { auto_id?: unknown }
    return !!p?.auto_id
  } catch {
    return false
  }
}

const AUDIT_FIELDS = new Set([
  'id',
  'sort',
  'user_created',
  'user_updated',
  'date_created',
  'date_updated',
  'created_at',
  'updated_at',
  'creator',
  'workspace_id'
])

/** Name-aware value generation. Returns undefined = "no idea, use type fallback". */
function fakeByName(rng: Rng, name: string, i: number): unknown {
  const n = name.toLowerCase()
  if (n === 'first_name' || n.endsWith('_first_name')) return pick(rng, FIRST_NAMES)
  if (n === 'last_name' || n.endsWith('_last_name')) return pick(rng, LAST_NAMES)
  if (n.includes('email')) {
    return `${pick(rng, FIRST_NAMES).toLowerCase()}.${pick(rng, LAST_NAMES).toLowerCase()}${i}@example.com`
  }
  if (n.includes('phone') || n.includes('mobile') || n === 'fax') {
    return `+1${int(rng, 200, 989)}555${String(int(rng, 0, 9999)).padStart(4, '0')}`
  }
  if (n.includes('city')) return pick(rng, CITIES)
  if (n === 'state' || n.endsWith('_state')) return pick(rng, STATES)
  if (n.includes('zip') || n.includes('postal')) return String(int(rng, 10000, 99999))
  if (n.includes('address') || n.includes('street')) {
    return `${int(rng, 100, 9899)} ${pick(rng, STREETS)}`
  }
  if (n.includes('company') || n.includes('vendor') || n.includes('organization')) {
    return pick(rng, COMPANIES)
  }
  if (n.includes('url') || n.includes('website') || n.includes('link')) {
    return `https://example.com/${pick(rng, WORDS)}-${i}`
  }
  if (n.includes('description') || n.includes('note') || n.includes('comment') || n.includes('summary')) {
    return pick(rng, SENTENCES)
  }
  if (n.includes('color') || n.includes('colour')) return `#${fakeHex(rng, 6)}`
  if (n === 'name' || n.endsWith('_name') || n === 'title' || n === 'label' || n === 'subject') {
    return `${pick(rng, WORDS)[0].toUpperCase()}${pick(rng, WORDS).slice(1)} ${pick(rng, WORDS)} ${i + 1}`
  }
  return undefined
}

function fakeByType(rng: Rng, f: FieldMeta, name: string): unknown {
  const t = String(f.type ?? 'string').toLowerCase()
  const n = name.toLowerCase()
  if (t === 'boolean' || t === 'bit') return rng() < 0.5
  if (['integer', 'bigint', 'biginteger', 'int', 'smallint', 'tinyint'].includes(t)) {
    if (n.includes('percent') || n.includes('progress') || n.includes('pct')) return int(rng, 0, 100)
    if (n.includes('qty') || n.includes('quantity') || n.includes('count')) return int(rng, 1, 100)
    if (n.includes('year')) return int(rng, 2020, 2030)
    if (n.includes('rating')) return int(rng, 1, 5)
    return int(rng, 1, 1000)
  }
  if (['decimal', 'float', 'numeric', 'money', 'real', 'double', 'number'].includes(t)) {
    if (n.includes('price') || n.includes('amount') || n.includes('cost') || n.includes('total') || n.includes('budget')) {
      return Math.round(rng() * 999_000 + 1000) / 100
    }
    return Math.round(rng() * 100_000) / 100
  }
  if (t === 'date') return fakeDate(rng).slice(0, 10)
  if (t === 'datetime' || t === 'timestamp') return fakeDate(rng)
  if (t === 'uuid' || t === 'uniqueidentifier') {
    return `${fakeHex(rng, 8)}-${fakeHex(rng, 4)}-4${fakeHex(rng, 3)}-a${fakeHex(rng, 3)}-${fakeHex(rng, 12)}`
  }
  if (t === 'json') return undefined
  // string/text fallback
  return `${pick(rng, WORDS)} ${pick(rng, WORDS)}`
}

export async function testDataRoutes(app: FastifyInstance): Promise<void> {
  app.post<{
    Params: { collection: string }
    Body: {
      count?: number
      respect_required?: boolean
      allow_nonempty?: boolean
      seed?: number
    }
  }>('/test-data/:collection', { preHandler: [requireAdmin] }, async (req, reply) => {
    const { collection } = req.params
    if (!TABLE_NAME_RE.test(collection) || /^(nivaro_|directus_|sys)/i.test(collection)) {
      return reply.code(400).send({ error: 'Business collections only' })
    }
    const meta = (await db('nivaro_collections').where({ collection }).first()) as
      | { collection: string; is_virtual?: boolean | number; singleton?: boolean | number }
      | undefined
    if (!meta) return reply.code(404).send({ error: `Collection "${collection}" is not registered` })
    if (meta.is_virtual) {
      return reply.code(400).send({ error: 'Virtual collections cannot receive generated rows' })
    }

    const countReq = Number(req.body?.count ?? 10)
    const count = Number.isFinite(countReq) ? Math.max(1, Math.min(MAX_COUNT, Math.floor(countReq))) : 10
    const respectRequired = req.body?.respect_required !== false
    const seedNum = Number(req.body?.seed)
    const rng = mulberry32(Number.isFinite(seedNum) ? seedNum : Math.floor(Math.random() * 2 ** 31))

    // Never seed a collection that already holds data unless explicitly allowed.
    const existing = (await db(collection).count('* as c').first()) as { c: number } | undefined
    const existingCount = Number(existing?.c ?? 0)
    if (existingCount > 0 && req.body?.allow_nonempty !== true) {
      return reply.code(409).send({
        error: `"${collection}" already has ${existingCount} row(s) — pass allow_nonempty to generate anyway`,
        existing_rows: existingCount
      })
    }

    // Physical columns — metadata rows for aliases/virtual fields never receive values.
    const physical = new Set(
      rawRows<{ COLUMN_NAME: string }>(
        await db.raw(
          `SELECT COLUMN_NAME AS "COLUMN_NAME" FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = ?`,
          [collection]
        )
      ).map((r) => r.COLUMN_NAME)
    )

    const fields = (await getFields(collection)) as unknown as FieldMeta[]
    const usable = fields.filter(
      (f) =>
        physical.has(f.field) &&
        !AUDIT_FIELDS.has(f.field.toLowerCase()) &&
        !f.computed_type &&
        !hasAutoId(f.options) &&
        String(f.type ?? '') !== 'alias'
    )

    // M2O FKs sample from EXISTING target rows (skip when the target is empty —
    // inventing FK values would violate constraints or dangle).
    const m2oRels = (await db('nivaro_relations')
      .where({ many_collection: collection })
      .whereNull('junction_field')
      .whereNotNull('one_collection')
      .select('many_field', 'one_collection')) as Array<{
      many_field: string
      one_collection: string
    }>
    const fkSamples = new Map<string, unknown[]>()
    for (const rel of m2oRels) {
      if (!TABLE_NAME_RE.test(rel.one_collection)) continue
      try {
        const ids = (await db(rel.one_collection).select('id').limit(50)) as Array<{ id: unknown }>
        if (ids.length > 0) {
          fkSamples.set(
            rel.many_field,
            ids.map((r) => r.id)
          )
        }
      } catch {
        // unreadable target — skip the FK entirely
      }
    }

    const created: unknown[] = []
    const errors: Array<{ row: number; error: string }> = []
    for (let i = 0; i < count; i++) {
      const row: Record<string, unknown> = {}
      for (const f of usable) {
        const required = !!f.required
        // Sparse realism: optional fields stay empty ~15% of the time.
        if (!required && rng() < 0.15) continue
        if (fkSamples.has(f.field)) {
          row[f.field] = pick(rng, fkSamples.get(f.field) as unknown[])
          continue
        }
        // An M2O column whose target has no rows: leave optional ones empty;
        // a required one has nothing valid to hold — skip and let validation speak.
        if (m2oRels.some((r) => r.many_field === f.field)) continue
        const choices = parseChoices(f.options)
        if (choices.length > 0) {
          row[f.field] = pick(rng, choices)
          continue
        }
        const byName = fakeByName(rng, f.field, i)
        const v = byName !== undefined ? byName : fakeByType(rng, f, f.field)
        if (v !== undefined) row[f.field] = v
        else if (required && respectRequired) row[f.field] = `Sample ${f.field} ${i + 1}`
      }
      try {
        const rec = (await createOne(req.user!, collection, row, req)) as { id?: unknown }
        created.push(rec?.id ?? null)
      } catch (err) {
        errors.push({
          row: i + 1,
          error: err instanceof Error ? err.message.slice(0, 300) : String(err).slice(0, 300)
        })
      }
    }

    await logActivity({
      action: 'test-data-generate',
      collection,
      user: req.user?.id,
      req,
      comment: `${created.length} of ${count} sample rows created`
    })
    return reply.send({ data: { created, errors, requested: count } })
  })
}
