// Client mirror of the help-video shapes. The edit types are copied from
// api/src/services/help-video-edits.ts and the DTOs from
// api/src/services/help-videos.ts (serializeVideo / serializeVersion) — keep
// them in step. All edit times are SOURCE time; rects are frame fractions.

export type Rect = { x: number; y: number; w: number; h: number }
export type Point = { x: number; y: number }
export type Speed = 0.5 | 1 | 1.5 | 2 | 4
/** A `step` is a callout with a number badge (numbered in timeline order);
 *  a `spotlight` dims the whole frame except its rect. */
export type AnnotationType = 'callout' | 'arrow' | 'box' | 'ripple' | 'step' | 'spotlight'
/** How every step badge looks (stored only when not STEP_STYLE_DEFAULTS). */
export interface StepStyle {
  shape: 'circle' | 'square'
  size: 'small' | 'medium' | 'large'
}
export type Tone = 'accent' | 'warning' | 'neutral'
export interface Segment {
  start_ms: number
  end_ms: number
  speed: Speed
  /** Music level under this piece, a share of the music volume (0 = none).
   *  Stored only when the music is on and the share is not 1. */
  music?: number
}
export interface Chapter {
  id: string
  at_ms: number
  title: string
}
export interface Annotation {
  id: string
  type: AnnotationType
  start_ms: number
  end_ms: number
  rect: Rect
  to: Point | null
  text: string
  tone: Tone
}
/** One stop of a moving zoom (#1539): the area shown at `at_ms` (source
 *  time), a square in frame fractions like `Zoom.rect`. */
export interface ZoomKeyframe {
  at_ms: number
  rect: Rect
}
export interface Zoom {
  id: string
  start_ms: number
  end_ms: number
  /** The area shown; with keyframes, always the first keyframe's area. */
  rect: Rect
  ease_ms: number
  /** A zoom that moves (#1539): the area pans and resizes straight-line
   *  between these stops (the first held before it, the last after it).
   *  Stored only with two or more stops, sorted, inside the zoom's span. */
  keyframes?: ZoomKeyframe[]
}
export interface Blur {
  id: string
  start_ms: number
  end_ms: number
  rect: Rect
  strength: number
}
export interface Caption {
  id: string
  start_ms: number
  end_ms: number
  text: string
}
/** A title card before the recording (real extra edited time). Blank
 *  `title` / `subtitle` mean the video's title and the first line of its
 *  description. */
export interface IntroCard {
  enabled: true
  duration_ms: number
  show_chapters: boolean
  title: string
  subtitle: string
  /** How the card's elements arrive (absent = none, a still card). */
  animation?: 'subtle' | 'lively'
  /** How the card hands over to the recording (absent = a cut). */
  transition?: 'fade' | 'fade_black' | 'slide' | 'zoom' | 'wipe'
}
/** A music bed under the whole video, looped and lowered under narration.
 *  `track` is a library key or an uploaded music file's id. */
export interface MusicBed {
  enabled: true
  source: 'library' | 'upload'
  track: string
  name: string
  /** Level while nobody speaks, 0.05–1. */
  volume: number
  duck: boolean
}
/** One track of the music library (GET /help-videos/music). */
export interface MusicTrack {
  key: string
  title: string
  description: string
  duration_ms: number
  /** Generated by the server, or a file an administrator added. */
  kind: 'generated' | 'file'
}
/** Where an imported music file came from (CC0 / public domain only). */
export interface MusicOrigin {
  provider: 'openverse'
  id: string
  creator: string | null
  license: 'cc0' | 'pdm'
  license_url: string | null
  landing_url: string | null
  /** The site Openverse found it on (freesound, jamendo, wikimedia_audio…). */
  source: string | null
}
/** An uploaded music file (POST /help-videos/:id/music). */
export interface UploadedMusic {
  id: string
  name: string
  duration_ms: number
  /** Set when it was imported from Openverse. */
  origin?: MusicOrigin
}
/** One Openverse search result (GET /help-videos/music/openverse). */
export interface OpenverseTrack {
  id: string
  title: string
  creator: string | null
  license: 'cc0' | 'pdm'
  license_url: string | null
  duration_ms: number | null
  provider: string | null
  landing_url: string | null
  attribution: string | null
}
export interface OpenverseSearch {
  /** False when the instance switched Openverse off (HELP_VIDEO_OPENVERSE=off). */
  enabled: boolean
  results: OpenverseTrack[]
  page?: number
  page_count?: number
  result_count?: number
}
/** An end card after the recording. Blank `text` means OUTRO_DEFAULT_TEXT. */
export interface OutroCard {
  enabled: true
  duration_ms: number
  text: string
  /** How the card's elements arrive (absent = none, a still card). */
  animation?: 'subtle' | 'lively'
  /** How the card takes over from the recording (absent = a cut). */
  transition?: 'fade' | 'fade_black' | 'slide' | 'zoom' | 'wipe'
}
export interface VideoEdits {
  v: 1
  segments: Segment[]
  poster_ms: number
  chapters: Chapter[]
  annotations: Annotation[]
  zooms: Zoom[]
  blurs: Blur[]
  captions: Caption[]
  /** Stored only while switched on (absent = off). */
  intro?: IntroCard
  outro?: OutroCard
  chapter_banners?: true
  /** How chapter banners arrive and leave (stored only while banners are on;
   *  absent = they pop on and off). */
  banner_animation?: 'subtle' | 'lively'
  /** The name drawn on the cards instead of the instance name (stored only
   *  when filled in). */
  card_brand?: string
  /** The poster is this card instead of the frame at poster_ms (stored only
   *  while that card is on). */
  poster_card?: 'intro' | 'outro'
  /** Background music (stored only while switched on). */
  music?: MusicBed
  /** What viewers see of the recording (frame fractions); stored only when
   *  smaller than the whole frame. Other rects stay relative to the whole
   *  recorded frame; cards are always full frame. */
  crop?: Rect
  /** Step badge look; stored only when not STEP_STYLE_DEFAULTS. */
  step_style?: StepStyle
  /** Narration cleanup (#1519): loudness levelling + noise reduction in the
   *  render. Stored only while on; live playback plays the recording as is. */
  audio?: { improve: true }
  /** Text size in callouts, boxes and steps (#1551); stored only when not
   *  'medium'. */
  callout_text?: 'small' | 'large'
  /** How captions look to viewers who have not chosen their own (#1551);
   *  only the keys that differ from the default look are stored. */
  caption_style?: Partial<CaptionStyle>
  /** The recorded cursor (#1517): a highlighted pointer drawn over the
   *  picture along the recorded pointer path, and with `shortcuts` a badge
   *  for each keyboard shortcut pressed. Stored only while on. */
  cursor?: CursorEdits
}

/** The cursor switches (#1517): only `{ show: true }` (plus `shortcuts: true`)
 *  is ever stored; off = the key is absent. */
export interface CursorEdits {
  show: true
  shortcuts?: true
}

export type Visibility = { mode: 'everyone' | 'roles'; role_ids: string[] }
export type HelpVideoContext = {
  kind: 'collection' | 'page'
  key: string
  state_key: string | null
}
export type RenderStatus = 'none' | 'queued' | 'rendering' | 'ready' | 'failed' | 'unavailable'

export interface VersionDto {
  id: string
  version: number
  edits: VideoEdits
  edits_hash: string
  source_duration_ms: number | null
  width: number | null
  height: number | null
  render_status: RenderStatus
  render_progress: number | null
  render_error: string | null
  rendered_current: boolean
  /** Published version only: false when a non-author would get the 409
   *  HELP_VIDEO_PROCESSING ("still being prepared") from the stream. */
  playable?: boolean
  note: string | null
  created_at: string
  /** Draft, re-record and restore results only (recorder data). */
  /** Clicks on the recorded tab: `t_ms` source time, `x`/`y` frame fractions (0–1);
   *  recorded since #1486, also what was clicked (see RecordedClick). */
  clicks?: RecordedClick[] | null
  /** Microphone loudness 0–1, one value per 100 ms of source time. */
  levels?: number[] | null
  /** Draft load only: 'upload' when the source is a video file someone picked
   *  (it has no clicks and no microphone levels), else 'recording'. */
  source_kind?: 'recording' | 'upload'
  /** Draft load only (#1518): when the author was typing in a text field or
   *  idle (no input for 3 s+) on the recorded tab, in source time. Null for
   *  uploaded files and recordings made without it. */
  activity?: ActivitySpan[] | null
  /** Draft load only (#1517): where the pointer went on the recorded tab and
   *  which shortcuts were pressed. Null for uploaded files and recordings
   *  made without it (the cursor switches then have nothing to show). */
  pointer?: PointerPath | null
  /** Retention removed this version's files (#1531): the Versions tab says
   *  so and restore answers 409 HELP_VIDEO_VERSION_FILES_REMOVED. Optional:
   *  older servers. */
  files_removed_at?: string | null
}

/** One sample of the pointer path (#1517): source time and frame fractions
 *  (0–1) of the captured frame, like a click. */
export type PointerSample = { t_ms: number; x: number; y: number }
/** A keyboard shortcut pressed while recording (#1517): source time and the
 *  keys as `Meta+S`, `Ctrl+K`, `Shift+Tab`, `Enter`, `ArrowDown` (modifiers
 *  first, letters upper-case). Never text typed into a field. */
export type RecordedShortcut = { t_ms: number; keys: string }
/** The pointer path and shortcuts of a recording of the author's own tab. */
export type PointerPath = { samples: PointerSample[]; shortcuts: RecordedShortcut[] }

/** A stretch of the recording where the author was typing in a text field,
 *  or touched nothing at all (#1518). Never what was typed. */
export type ActivitySpan = {
  kind: 'typing' | 'idle'
  start_ms: number
  end_ms: number
}

/**
 * One click on the recorded tab: recording time and frame fractions (0–1).
 * When the recorder captured its own tab, also what was clicked: accessible
 * name (≤ 80 chars, never an input's value), role, nearest data-* hook
 * (`data-name` or `data-name=value`), the screen's page key, path and origin.
 * Inside `.nvr-no-record` only the position is kept.
 */
export type RecordedClick = {
  t_ms: number
  x: number
  y: number
  label?: string
  role?: string
  hook?: string
  page_key?: string
  path?: string
  origin?: string
}

/** One step of "Show me on this page" (GET /help-videos/:id/walk). */
export interface WalkStep {
  label: string
  role: string | null
  hook: string | null
  page_key: string | null
  path: string | null
  origin: string | null
  /** Where the step happens in the finished video (edited time). */
  edited_ms: number
  /** The callout or box text shown around the click, else null. */
  text: string | null
}

/** Ticketed download links (`attachment`), relative to the API origin. */
export interface DownloadUrls {
  video: string
  /** Null when the video has no captions. */
  captions_vtt: string | null
  captions_srt: string | null
}

export interface HelpVideoProgress {
  position_ms: number
  completed: boolean
  percent: number
}

export interface HelpVideoDto {
  id: string
  title: string
  description: string | null
  category: string | null
  status: 'draft' | 'published' | 'archived'
  duration_ms: number | null
  /** Ticketed URLs (`?st=`, relative to the API origin): use them as given,
   *  never rebuild them. Tickets expire after 3–6 hours. */
  poster_url: string | null
  stream_url: string | null
  captions_url: string | null
  contexts: HelpVideoContext[]
  /** Required for THIS viewer's role (not for the video in general). */
  required: boolean
  published: VersionDto | null
  // Authors only.
  visibility?: Visibility
  required_role_ids?: string[]
  draft?: VersionDto | null
  /** Author-only: the draft is exactly the published version (same recording,
   *  same edits), so publishing it would change nothing. */
  draft_matches_published?: boolean
  /** The draft's original recording (already carries `source=1`). */
  draft_stream_url?: string | null
  draft_captions_url?: string | null
  /** Author-only: the "Allow downloads" switch (for viewers; authors always may). */
  allow_downloads?: boolean
  /** Author-only: the draft's downloads (render when current, else the original). */
  draft_download_urls?: DownloadUrls | null
  created_by_name?: string | null
  /** Null when this person may not download the published version. A
   *  viewer's video link answers 409 HELP_VIDEO_PROCESSING while
   *  `published.playable` is false. */
  download_urls: DownloadUrls | null
  updated_at: string
  my_progress: HelpVideoProgress | null
  /** Ticketed plain-text transcript (captions under chapter headings) for
   *  anyone who can watch, whatever the "Allow downloads" switch says. Null
   *  when the published version has no captions. Optional: older servers. */
  transcript_url?: string | null
  /** What changed since this person last watched (#1497), else null. */
  whats_new?: HelpVideoWhatsNew | null
  /** The screen changed since this was published (#1495): a layout version,
   *  a renamed or removed pipeline step, or a recorded click label gone from
   *  the page. Null when nothing was found or an author dismissed it;
   *  publishing clears it. Optional: older servers. */
  stale?: HelpVideoStale | null
}

/** Why a video may be out of date (#1495). */
export interface HelpVideoStale {
  kind: 'layout' | 'state' | 'label'
  /** One sentence naming the change. */
  detail: string
  /** When the change happened (ISO). */
  since: string
}

/** `updated`: a newer version than the one watched is published; `again`: the
 *  author asked everyone to watch the same version again. */
export interface HelpVideoWhatsNew {
  kind: 'updated' | 'again'
  watched_version: number | null
  version: number
  /** The author's note for this version (system notes left out). */
  note: string | null
  /** Where "Jump to what changed" starts (edited time); null = nothing to jump to. */
  jump_ms: number | null
  chapter: { id: string; title: string } | null
  /** The recording itself was replaced: watch it from the start. */
  whole: boolean
}

/** How captions look in the player (#1529), remembered per person. */
export interface CaptionStyle {
  size: 's' | 'm' | 'l' | 'xl'
  background: 'none' | 'shaded' | 'solid'
  position: 'bottom' | 'top'
}

/** A question asked at a moment of the video (#1505; GET /help-videos/:id/questions).
 *  `text` and `answer` are what people wrote — data, shown as is. */
export interface HelpVideoQuestion {
  id: string
  video_id: string
  version_id: string | null
  /** Where it was asked, in the finished video (edited time). */
  at_ms: number
  text: string
  /** Asked by this person. */
  mine: boolean
  /** Authors only: who asked. */
  asked_by_name?: string | null
  answer: string | null
  answered_at: string | null
  answered_by_name: string | null
  created_at: string
}

/** Thumbs up / down counts (#1505). */
export interface HelpVideoRatingSummary {
  up: number
  down: number
  /** up / (up + down), 3 places; 0 with no votes. */
  helpful_rate: number
}

/** GET /help-videos/:id/analytics (authors). */
export interface HelpVideoAnalytics {
  views: number
  unique_viewers: number
  completion_rate: number
  /** Share of viewers who reached each 5% section (20 values). */
  drop_off: number[]
  watched_hours: number
  /** Absent on older servers. */
  ratings?: HelpVideoRatingSummary
  questions?: HelpVideoQuestion[]
}

/** Error codes the help-video routes answer with (`{ error, code }`). */
export type HelpVideoErrorCode =
  | 'HELP_VIDEO_PROCESSING'
  | 'HELP_VIDEO_EDITS_CONFLICT'
  | 'HELP_VIDEO_EDITS_INVALID'
  | 'HELP_VIDEO_NOT_FOUND'
  | 'HELP_VIDEO_AUTHOR_ONLY'
  | 'HELP_VIDEO_DOWNLOAD_OFF'
  | 'HELP_VIDEO_MASQUERADE'
  | 'HELP_VIDEO_RATING_INVALID'
  | 'HELP_VIDEO_QUESTION_INVALID'
  | 'HELP_VIDEO_QUESTION_NOT_FOUND'
  | 'HELP_VIDEO_NOT_STALE'
  | 'HELP_VIDEO_VERSION_FILES_REMOVED'
