// Full styled form from @nivaro/shared

// SDK re-exports (types useful in form consumers)
export type { CascadeFilterRule, FieldDependencyConfig } from '@nivaro/sdk'
// Expression engine result types (the functions were already exported)
export type {
  ApiVersionInfo,
  BannerLine,
  BaseMapBubble,
  BaseMapPin,
  ChangeReasonChallenge,
  ChatProviderProps,
  CollectionBrowserColumn,
  CollectionBrowserViewProps,
  CollectionUpdateEvent,
  Column,
  ColumnFormatConfig,
  CustomStatus,
  DataTableProps,
  DrilldownContextValue,
  DrilldownTarget,
  DrilldownViewOverride,
  EvaluateOptions,
  ExprNode,
  ExprValue,
  FieldDrilldownConfig,
  FieldInterfaceHandle,
  FieldInterfacePlugin,
  FieldInterfaceProps,
  FilterDef,
  FormulaEditorProps,
  FormulaField,
  GridFlushContextValue,
  HeaderWidgetInfo,
  IntegrationDotsProps,
  IntegrationObligationsViewProps,
  IntegrationStatusBannerProps,
  ItemEditAuthContextValue,
  ItemEditFormProps,
  ItemLinkTarget,
  LeaderSocketHandle,
  M2MStagingCtx,
  NavigationContextValue,
  ObligationFilterState,
  OverlayHistory,
  PageRendererPage,
  PageRendererProps,
  PageRendererWidget,
  ParseResult,
  QueueGroup,
  QueueRealtimeAdapter,
  QueueWorklistProps,
  QuickPickerDialogProps,
  QuickPickerProps,
  ReadViewLayout,
  RealtimeAdapter,
  RenderFieldProps,
  ReportViewProps,
  TokenResolver
} from '@nivaro/shared'
// ─── Realtime sprint 2026-08-24 ─────────────────────────────────────────────
// ─── Parity sweep 2026-08-19 — shared surfaces headless hosts need ──────────
// Feature components
// Panels — completes the set (siblings were already exported)
// Item-edit building blocks for hosts composing custom edit shells
// Imports
// Alerts — drawers + the data types AlertManagerView consumers handle
// DataTable typing surface (the component was exported, its props were not)
// Formatting + behavior libs hosts must match, not reimplement
// Context surface — value types + the optional-client/config hooks
// Chat — the rest of the hook set + channel admin surfaces
// Re-export sweep (2026-08-25): shared surface that headless hosts were
// missing — display-pref setters, the fiscal/formula/layout-slot libs,
// field-interface registry, and the utility components/hooks below.
export {
  ACTIVE_USER_OPTION_FILTER,
  AccessDeniedPanel,
  AddendumPanel,
  AiAnalyticsView,
  AiFeedbackButtons,
  AiMarkdown,
  AiReviewCard,
  AlertManagerView,
  type AlertManagerViewProps,
  AlertRuleDrawer,
  AnnouncementBanner,
  AnomalyRuleDrawer,
  ApiRequestLog,
  type ApiRequestLogFilters,
  ApiUpdateBanner,
  AutolinkedText,
  activeCustomStatus,
  agingBucket,
  applyValidationRule,
  BaseMap,
  BroadcastView,
  BulkActionButtons,
  bannerLines,
  buildGroups,
  CacheStamp,
  CellCopyLayer,
  ChangeReasonDialog,
  ChatChannelBrowser,
  ChatChannelSettings,
  type ChatConfig,
  type ChatMessage,
  type ChatOnlineUser,
  ChatPanel,
  ChatProvider,
  ChatRoomList,
  ChatRoomView,
  type ChatTheme,
  CloneDialog,
  CollectionBrowserView,
  CollectionImportPanel,
  CommandCenterView,
  CommentPanel,
  ConformanceView,
  CronBuilder,
  CustomActionButtons,
  CustomStatusEditor,
  canOpenCatalogItem,
  canOpenChatRoom,
  canOpenDm,
  canPreviewFile,
  changeReasonChallenge,
  chatAvatarColor,
  chatInitials,
  choiceLabel,
  createGatedClient,
  createLeaderSocket,
  DataTable,
  DefinitionsPanel,
  DelegationCard,
  DelegationConsoleView,
  type DelegationConsoleViewProps,
  DeliveryChips,
  DisplayPrefsCard,
  DrilldownContext,
  DrilldownViewsContext,
  decodePrefill,
  defaultItemUrl,
  deriveGroupKey,
  describeCron,
  dmPeer,
  dmRoom,
  dotsForRecord,
  EmptyState,
  ErpFailureBanner,
  type ErpSubmission,
  ErrorSurface,
  EventPathSheet,
  type EventPathSheetProps,
  ExternalRequestsChip,
  effectiveScopeSeedIds,
  encodePrefill,
  evaluateBoolean,
  evaluateExpression,
  evaluateNumeric,
  extractExpressionTokens,
  extSlotKey,
  FieldRenderer,
  FilePreviewLightbox,
  FilterControl,
  FirefightView,
  type FirefightViewProps,
  FirstLoginChecklist,
  FORCE_RELOAD_EVENT,
  ForceReloadBanner,
  type ForceReloadDetail,
  FormulaEditor,
  fieldDrilldownConfig,
  filterDefLabel,
  filterValueDisplay,
  fiscalPeriodOf,
  fiscalQuarterOf,
  fiscalYearOf,
  formatDate,
  formatDateTime,
  formatFileSize,
  formatMultiValue,
  formatNumber,
  formatRelative,
  formatStatusExpiry,
  formatValue,
  formulaConstant,
  type GatedClient,
  GridFlushContext,
  getApiUpdate,
  getFieldInterface,
  getFiscalStartMonth,
  getLayoutSlot,
  getMentionQuery,
  HScrollProxy,
  IDLE_AFTER_MS,
  ImportConsole,
  type ImportConsoleProps,
  type ImportConsoleTab,
  ImportDefaultCadenceControl,
  type ImportDefinition,
  ImportFromFileButton,
  type ImportHealthRow,
  ImportIssuesPanel,
  type ImportJob,
  type ImportJobStatus,
  type ImportPreview,
  type ImportProgressEvent,
  type ImportRealtimeAdapter,
  type ImportRun,
  type ImportRunStatus,
  ImportStalenessChip,
  ImportStalenessControl,
  type ImportStalenessControlProps,
  type ImportStats,
  INTEGRATIONS_FILTER_OPTIONS,
  InactiveUserLinksView,
  InboundCallersView,
  InboundView,
  type InboundViewProps,
  InlineTableField,
  type IntegrationActionResult,
  IntegrationDots,
  type IntegrationEventPath,
  type IntegrationEventPathTarget,
  IntegrationObligationsView,
  type IntegrationPartnerCard,
  type IntegrationPartnerDetail,
  type IntegrationPartnerHealth,
  type IntegrationPartnersSummary,
  type IntegrationPathDetail,
  type IntegrationPathNode,
  type IntegrationSignalAction,
  type IntegrationSignalRow,
  type IntegrationSignalsSnapshot,
  type IntegrationSignalView,
  IntegrationStatusBanner,
  IntegrationsConsole,
  type IntegrationsConsoleProps,
  type IntegrationsConsoleTab,
  ItemActionButtons,
  ItemEditAuthContext,
  ItemEditForm,
  ItemLockBanner,
  idleState,
  JsonMapEditor,
  listFieldInterfaces,
  MatrixEditor,
  MyWorkView,
  matchScopeDimension,
  NavigationContext,
  NewImportDialog,
  type NotificationActionSpec,
  NotificationActions,
  NotificationAnalyticsView,
  NotificationBell,
  type NotificationBellProps,
  NotificationCenterView,
  type NotificationCenterViewProps,
  type NotificationDeliveryRecord,
  type NotificationLane,
  type NotificationLike,
  type NotificationRouteMap,
  NotificationRulesCard,
  type NotificationSound,
  NotificationSourcesCard,
  NotificationSubscriptionsView,
  type NotificationTarget,
  type NotificationTargetSpec,
  NotificationTemplatesView,
  networkdaysBetween,
  numericIntlOptions,
  OfflineBanner,
  OverlayHistoryContext,
  OwnerAvatars,
  OwnerGapsCard,
  OwnerMatrix,
  OwnersSlot,
  obligationQueryParams,
  onFieldInterfacesChange,
  onIdleChange,
  openCatalogItem,
  openChatRoom,
  openDmWith,
  PageRenderer,
  PartnerDetail,
  type PartnerDetailProps,
  PartnersView,
  type PartnersViewProps,
  type PipelineEditorSection,
  PipelineEditorView,
  PipelinePanel,
  PipelineSimulatorCard,
  PipelineTransitionButtons,
  ProfileFieldsCard,
  ProfileView,
  parseExpression,
  playNotificationSound,
  precisionOf,
  QualityRulesView,
  QueryStatStrip,
  QueryTable,
  QueryWidgetBody,
  QueryWidgetView,
  QueueBulkBar,
  QueueItemSheet,
  QueueKanbanBoard,
  QueueWorklist,
  QueueWorkloadView,
  QuickPicker,
  QuickPickerDialog,
  REACTION_EMOJI,
  RealtimeContext,
  RecentRecordsRail,
  RecordChatActions,
  RecordDrilldownSheet,
  RecordGridEditor,
  RecordGridWidgetBody,
  RecordReadView,
  RecordRecapStrip,
  RecordSubscribeButton,
  RelatedRecordsPanel,
  RelationCombobox,
  ReportView,
  ReviewListWidget,
  RevisionsPanel,
  ROW_HIGHLIGHT_TINTS,
  type RoomInfo,
  rankSignals,
  rankTeamForFilters,
  registerCatalogItemOpener,
  registerDmOpener,
  registerFieldInterface,
  registerLayoutSlot,
  registerRoomOpener,
  resolveCollectionIcon,
  resolveNotificationTarget,
  resolveNotificationTargetFor,
  rowHighlightClass,
  rowHighlightTextClass,
  rumRouteChange,
  runNotificationTarget,
  SignalCard,
  type SignalCardProps,
  type SlaRule,
  SlaRulesView,
  type SnoozeInput,
  SnoozeMenu,
  SubmissionRow,
  SubmissionStatusPill,
  SubscriptionDialog,
  seedQuickPickerSteps,
  setDisplayTimezone,
  setFiscalStartMonth,
  setFormulaConstants,
  setNumberFormat,
  setTimeDisplay,
  splitMessageTokens,
  startApiVersionWatch,
  startRum,
  TaskPanel,
  TeamScopeEditor,
  TeamsView,
  TickerNumber,
  TimezoneCard,
  TipLayer,
  titleCase,
  toneForOutcome,
  trackActivity,
  translateScopeValues,
  UserAvatar,
  UserChip,
  UserRosterCluster,
  useAfterIdle,
  useApiFetchConfig,
  useApiUpdate,
  useAvailableBulkActions,
  useChannelAdmin,
  useChannelDirectory,
  useChannelMembers,
  useChatConfig,
  useChatMessages,
  useChatRoles,
  useChatRooms,
  useChatSearch,
  useCreateChannel,
  useCreateGroupDm,
  useDebounced,
  useDeleteMessage,
  useDrilldown,
  useDrilldownViews,
  useEditMessage,
  useElapsedLoading,
  useEntityRoomLink,
  useEventPath,
  useFeatureFlag,
  useFeatureFlags,
  useFileHealth,
  useGridFlush,
  useImportHealth,
  useItemEditAuth,
  useItemLock,
  useItemNavigation,
  useMarkRoomRead,
  useMyScopes,
  useNavigation,
  useOnlineUsers,
  useOptionalNivaroClient,
  useOptionalRealtime,
  useOverlayState,
  usePartner,
  usePartners,
  usePeerReadAt,
  useQuickPickerSteps,
  useRecordIntegrationActivity,
  useRefreshSignals,
  useRoomMembership,
  useRoomPins,
  useScopeDimensions,
  useSendChatMessage,
  useSetImportCadence,
  useSignalAction,
  useSignals,
  useSnooze,
  useSubscriptionMutations,
  useTogglePin,
  useToggleReaction,
  useTypingIndicator,
  useUnreadChirp,
  useUserSearch,
  validateExpression,
  WidgetSlot,
  WorkflowPanel,
  withGetCoalescing
} from '@nivaro/shared'
export { BooleanField } from './components/fields/BooleanField'
export { DateField } from './components/fields/DateField'
export { FileField } from './components/fields/FileField'
export { NumberField } from './components/fields/NumberField'
export { RelationField } from './components/fields/RelationField'
export { SelectField } from './components/fields/SelectField'
export { TextareaField } from './components/fields/TextareaField'
export { TextField } from './components/fields/TextField'
export type { SlotRendererProps } from './components/LayoutForm'
export { LayoutForm } from './components/LayoutForm'
export { NivaroField } from './components/NivaroField'
// Components
export { NivaroForm } from './components/NivaroForm'
// Context
export { NivaroProvider, useNivaroClient } from './context'
export {
  clearFormSchemaCache,
  fetchSchema,
  normalizeFieldType,
  useFormSchema
} from './hooks/useFormSchema'
export type {
  FieldArrayReturn,
  FieldState,
  FormDirtyState,
  FormStatus,
  LayoutItem,
  SectionState,
  TabState
} from './hooks/useLayoutHooks'
// Layout hooks
export {
  useFieldArray,
  useFieldState,
  useFormDirty,
  useFormStatus,
  useOrderedLayout,
  useSectionState,
  useTabState,
  useWatchFields
} from './hooks/useLayoutHooks'
// Hooks
export { useNivaroForm } from './hooks/useNivaroForm'
export type { RelationOption } from './hooks/useRelationOptions'
export { useRelationOptions } from './hooks/useRelationOptions'
export {
  captureErrorClip,
  type ErrorReplayLink,
  type SessionRecorderOptions,
  useSessionRecorder
} from './hooks/useSessionRecorder'
// Types
export type {
  ComponentOverrides,
  FieldComponentProps,
  FormErrors,
  FormFieldDescriptor,
  FormFieldType,
  FormGroupDescriptor,
  FormLockCondition,
  FormSchema,
  FormSlotAssignment,
  FormValidationRule,
  FormVisibilityRule,
  UseNivaroFormOptions,
  UseNivaroFormReturn
} from './types'
