import type { Knex } from 'knex'

// Cross-dialect helper — creates table only if it doesn't already exist.
// Safe for both fresh installs and upgrades from a pre-migration schema.
async function create(knex: Knex, table: string, fn: (t: Knex.TableBuilder) => void) {
  if (!(await knex.schema.hasTable(table))) {
    await knex.schema.createTable(table, fn)
  }
}

export async function up(knex: Knex): Promise<void> {
  // ── Leaf tables (no FK deps) ──────────────────────────────────────────────

  await create(knex, 'nivaro_activity', (t) => {
    t.increments('id').primary()
    t.string('action', 50).notNullable()
    t.uuid('user')
    t.datetime('timestamp').notNullable().defaultTo(knex.fn.now())
    t.string('ip', 50)
    t.string('user_agent', 500)
    t.string('collection', 255)
    t.string('item', 255)
    t.text('comment')
    t.index(['collection', 'item'])
    t.index(['user'])
    t.index(['timestamp'])
  })

  await create(knex, 'nivaro_api_logs', (t) => {
    t.bigIncrements('id').primary()
    t.string('method', 10).notNullable()
    t.string('path', 500).notNullable()
    t.integer('status').notNullable()
    t.integer('latency_ms').notNullable()
    t.string('user', 100)
    t.string('collection', 100)
    t.datetime('created_at').defaultTo(knex.fn.now())
    t.index(['created_at'])
  })

  await create(knex, 'nivaro_attribute_values', (t) => {
    t.increments('id').primary()
    t.string('collection', 255).notNullable()
    t.string('item_id', 255).notNullable()
    t.string('attribute_key', 255).notNullable()
    t.text('value')
    t.datetime('updated_at').defaultTo(knex.fn.now())
    t.unique(['collection', 'item_id', 'attribute_key'])
  })

  await create(knex, 'nivaro_blackout_dates', (t) => {
    t.increments('id').primary()
    t.date('date').notNullable().unique()
    t.string('label', 255)
    t.text('scope')
    t.datetime('created_at').defaultTo(knex.fn.now())
  })

  await create(knex, 'nivaro_collection_layouts', (t) => {
    t.increments('id').primary()
    t.string('collection', 255).notNullable()
    t.string('name', 255).notNullable()
    t.boolean('is_active').notNullable().defaultTo(false)
    t.integer('sort').notNullable().defaultTo(0)
    t.datetime('created_at').defaultTo(knex.fn.now())
    t.unique(['collection', 'name'])
  })

  await create(knex, 'nivaro_custom_queries', (t) => {
    t.increments('id').primary()
    t.string('name', 255).notNullable()
    t.text('description')
    t.string('slug', 255).notNullable().unique()
    t.text('sql_text').notNullable()
    t.text('params')
    t.integer('cache_ttl').notNullable().defaultTo(0)
    t.boolean('enabled').notNullable().defaultTo(true)
    t.string('access', 50).notNullable().defaultTo('admin')
    t.datetime('created_at').defaultTo(knex.fn.now())
    t.datetime('updated_at').defaultTo(knex.fn.now())
  })

  await create(knex, 'nivaro_dq_rules', (t) => {
    t.increments('id').primary()
    t.string('collection', 100).notNullable()
    t.string('name', 255).notNullable()
    t.string('rule_type', 20).notNullable()
    t.string('field', 100)
    t.text('config')
    t.string('severity', 20).notNullable().defaultTo('medium')
    t.boolean('is_active').notNullable().defaultTo(true)
    t.datetime('created_at').defaultTo(knex.fn.now())
  })

  await create(knex, 'nivaro_embeddings', (t) => {
    t.bigIncrements('id').primary()
    t.string('collection', 100).notNullable()
    t.string('item', 100).notNullable()
    t.string('field', 100).notNullable()
    t.string('content_hash', 64).notNullable()
    t.text('embedding').notNullable()
    t.datetime('updated_at').defaultTo(knex.fn.now())
    t.unique(['collection', 'item', 'field'])
  })

  await create(knex, 'nivaro_external_apis', (t) => {
    t.increments('id').primary()
    t.string('name', 255).notNullable()
    t.string('base_url', 1000).notNullable()
    t.text('description')
    t.string('auth_type', 50).notNullable().defaultTo('none')
    t.text('auth_config')
    t.text('headers')
    t.boolean('enabled').notNullable().defaultTo(true)
    t.datetime('created_at').defaultTo(knex.fn.now())
    t.datetime('updated_at').defaultTo(knex.fn.now())
    t.string('integration_type', 100)
    t.text('integration_config')
  })

  await create(knex, 'nivaro_external_api_logs', (t) => {
    t.increments('id').primary()
    t.integer('api_id').notNullable()
    t.integer('endpoint_id')
    t.string('triggered_by', 100).notNullable().defaultTo('unknown')
    t.string('method', 10).notNullable()
    t.string('url', 2048).notNullable()
    t.text('request_headers')
    t.text('request_body')
    t.integer('response_status')
    t.text('response_headers')
    t.text('response_body')
    t.integer('duration_ms')
    t.string('error', 2000)
    t.string('user_id', 255)
    t.datetime('created_at').notNullable().defaultTo(knex.fn.now())
  })

  await create(knex, 'nivaro_page_views', (t) => {
    t.bigIncrements('id').primary()
    t.string('session_id', 64).notNullable()
    t.string('user_id', 128)
    t.string('user_email', 254)
    t.string('user_name', 128)
    t.string('page_url', 2048).notNullable()
    t.string('page_title', 256)
    t.string('referrer', 2048)
    t.string('device_type', 16)
    t.string('ip', 45)
    t.string('user_agent', 500)
    t.datetime('viewed_at').notNullable().defaultTo(knex.fn.now())
    t.integer('duration_seconds')
  })

  await create(knex, 'nivaro_relations', (t) => {
    t.increments('id').primary()
    t.string('many_collection', 255).notNullable()
    t.string('many_field', 255).notNullable()
    t.string('one_collection', 255)
    t.string('one_field', 255)
    t.string('one_collection_field', 255)
    t.text('one_allowed_collections')
    t.string('junction_field', 255)
    t.string('sort_field', 255)
    t.string('one_deselect_action', 50).notNullable().defaultTo('nullify')
  })

  await create(knex, 'nivaro_sequences', (t) => {
    t.string('id', 255).primary()
    t.bigInteger('next_val').defaultTo(1).notNullable()
  })

  await create(knex, 'nivaro_settings', (t) => {
    t.increments('id').primary()
    t.string('project_name', 255).notNullable().defaultTo('Nivaro')
    t.string('project_url', 500)
    t.string('project_color', 50).notNullable().defaultTo('#00ceff')
    t.string('default_language', 20).notNullable().defaultTo('en-US')
    t.datetime('updated_at').notNullable().defaultTo(knex.fn.now())
    t.string('project_description', 500)
    t.string('teams_webhook_url', 500)
    t.text('ad_group_role_map')
    t.string('anthropic_api_key', 500)
    t.integer('presence_session_ttl').defaultTo(20)
    t.integer('presence_sweep_interval').defaultTo(8000)
    t.integer('presence_ping_interval').defaultTo(10000)
    t.string('ai_model', 100).defaultTo('claude-haiku-4-5-20251001')
    t.integer('ai_max_tokens_generate').defaultTo(500)
    t.integer('ai_max_tokens_summarize').defaultTo(200)
    t.integer('sla_business_day_start').defaultTo(9)
    t.integer('sla_business_day_end').defaultTo(17)
    t.string('sla_business_days', 20).defaultTo('1,2,3,4,5')
    t.integer('file_max_size_mb').defaultTo(50)
    t.integer('collection_page_size').defaultTo(25)
    t.integer('activity_retention_days')
    t.integer('revision_retention_count')
    t.text('available_locales')
    t.string('smtp_host', 255)
    t.integer('smtp_port')
    t.string('smtp_user', 255)
    t.string('smtp_pass', 500)
    t.string('smtp_from', 255)
    t.boolean('smtp_secure')
    t.string('sms_provider', 50)
    t.string('sms_account_sid', 255)
    t.string('sms_auth_token', 500)
    t.string('sms_from', 100)
    t.string('sms_region', 50)
  })

  await create(knex, 'nivaro_webhooks', (t) => {
    t.increments('id').primary()
    t.string('name', 255).notNullable()
    t.text('events').notNullable().defaultTo('["create","update","delete"]')
    t.string('url', 2000).notNullable()
    t.string('method', 10).notNullable().defaultTo('POST')
    t.text('headers')
    t.string('secret', 500)
    t.boolean('enabled').notNullable().defaultTo(true)
    t.datetime('created_at').defaultTo(knex.fn.now())
    t.datetime('updated_at').defaultTo(knex.fn.now())
    t.text('collections')
    t.string('signing_secret', 255)
  })

  await create(knex, 'nivaro_file_folders', (t) => {
    t.uuid('id').primary().defaultTo(knex.fn.uuid())
    t.string('name', 255).notNullable()
    t.uuid('parent').references('id').inTable('nivaro_file_folders')
  })

  await create(knex, 'nivaro_flows', (t) => {
    t.uuid('id').primary().defaultTo(knex.fn.uuid())
    t.string('name', 255).notNullable()
    t.text('description')
    t.string('status', 50).notNullable().defaultTo('inactive')
    t.string('trigger', 100).notNullable()
    t.text('trigger_options')
    t.string('accountability', 50).notNullable().defaultTo('all')
    t.datetime('created_at').notNullable().defaultTo(knex.fn.now())
    t.datetime('updated_at').notNullable().defaultTo(knex.fn.now())
  })

  await create(knex, 'nivaro_workflow_templates', (t) => {
    t.uuid('id').primary().defaultTo(knex.fn.uuid())
    t.string('name', 255).notNullable()
    t.text('description')
    t.string('color', 50)
    t.string('icon', 100)
    t.datetime('created_at').notNullable().defaultTo(knex.fn.now())
    t.datetime('updated_at').notNullable().defaultTo(knex.fn.now())
  })

  await create(knex, 'nivaro_ai_collection_settings', (t) => {
    t.increments('id').primary()
    t.string('collection', 100).notNullable().unique()
    t.boolean('validation_enabled').notNullable().defaultTo(false)
    t.string('validation_mode', 10).notNullable().defaultTo('soft')
    t.text('validation_rules')
    t.boolean('duplicate_detection_enabled').notNullable().defaultTo(false)
    t.float('duplicate_threshold').notNullable().defaultTo(0.85)
    t.datetime('created_at').defaultTo(knex.fn.now())
    t.datetime('updated_at').defaultTo(knex.fn.now())
  })

  // ── Depends on nivaro_workflow_templates ──────────────────────────────────

  await create(knex, 'nivaro_workflow_states', (t) => {
    t.uuid('id').primary().defaultTo(knex.fn.uuid())
    t.uuid('template').notNullable().references('id').inTable('nivaro_workflow_templates').onDelete('CASCADE')
    t.string('key', 100).notNullable()
    t.string('label', 255).notNullable()
    t.string('color', 50)
    t.boolean('is_initial').notNullable().defaultTo(false)
    t.boolean('is_terminal').notNullable().defaultTo(false)
    t.boolean('lock_record').notNullable().defaultTo(false)
    t.integer('sort').notNullable().defaultTo(0)
    t.text('skip_criteria')
    t.boolean('skip_if_no_owners').notNullable().defaultTo(false)
    t.string('stage_visibility', 32).notNullable().defaultTo('always')
    t.index(['template'])
  })

  // ── Depends on nivaro_collection_layouts ─────────────────────────────────

  await create(knex, 'nivaro_field_groups', (t) => {
    t.increments('id').primary()
    t.string('collection', 255).notNullable()
    t.string('key', 100).notNullable()
    t.string('label', 255).notNullable()
    t.string('type', 20).notNullable().defaultTo('section')
    t.string('icon', 100)
    t.integer('sort').notNullable().defaultTo(0)
    t.boolean('is_collapsed').notNullable().defaultTo(false)
    t.integer('layout_id').references('id').inTable('nivaro_collection_layouts')
  })

  await create(knex, 'nivaro_layout_field_assignments', (t) => {
    t.increments('id').primary()
    t.integer('layout_id').notNullable().references('id').inTable('nivaro_collection_layouts')
    t.string('field', 255).notNullable()
    t.string('group_key', 255)
    t.integer('sort').notNullable().defaultTo(0)
    t.unique(['layout_id', 'field'])
  })

  // ── Depends on nivaro_external_apis ──────────────────────────────────────

  await create(knex, 'nivaro_external_api_endpoints', (t) => {
    t.increments('id').primary()
    t.integer('api_id').notNullable().references('id').inTable('nivaro_external_apis').onDelete('CASCADE')
    t.string('name', 255).notNullable()
    t.string('method', 20).notNullable().defaultTo('GET')
    t.string('path', 2000).notNullable().defaultTo('')
    t.text('description')
    t.text('default_body')
    t.text('default_query')
    t.text('default_headers')
    t.integer('sort').notNullable().defaultTo(0)
    t.datetime('created_at').defaultTo(knex.fn.now())
    t.datetime('updated_at').defaultTo(knex.fn.now())
    t.string('slug', 100)
  })

  // ── Core CMS tables ───────────────────────────────────────────────────────

  await create(knex, 'nivaro_workspaces', (t) => {
    t.uuid('id').primary()
    t.string('name', 255).notNullable()
    t.string('slug', 100).notNullable().unique()
    t.string('icon', 100)
    t.string('color', 20)
    t.datetime('created_at').notNullable().defaultTo(knex.fn.now())
    t.datetime('updated_at').notNullable().defaultTo(knex.fn.now())
    t.text('quotas')
  })

  await create(knex, 'nivaro_roles', (t) => {
    t.uuid('id').primary().defaultTo(knex.fn.uuid())
    t.string('name', 255).notNullable().unique()
    t.text('description')
    t.boolean('admin_access').notNullable().defaultTo(false)
    t.boolean('app_access').notNullable().defaultTo(true)
    t.datetime('created_at').notNullable().defaultTo(knex.fn.now())
    t.datetime('updated_at').notNullable().defaultTo(knex.fn.now())
    t.uuid('workspace').references('id').inTable('nivaro_workspaces')
    t.text('ui_permissions')
  })

  await create(knex, 'nivaro_users', (t) => {
    t.uuid('id').primary().defaultTo(knex.fn.uuid())
    t.string('first_name', 255)
    t.string('last_name', 255)
    t.string('email', 255).notNullable().unique()
    t.string('external_id', 500)
    t.uuid('role').references('id').inTable('nivaro_roles').onDelete('SET NULL')
    t.string('status', 50).notNullable().defaultTo('active')
    t.datetime('last_access')
    t.string('last_page', 500)
    t.text('preferences')
    t.datetime('created_at').notNullable().defaultTo(knex.fn.now())
    t.datetime('updated_at').notNullable().defaultTo(knex.fn.now())
    t.uuid('avatar')
    t.string('static_token', 64).unique()
    t.uuid('current_workspace').references('id').inTable('nivaro_workspaces')
    t.uuid('manager_id').references('id').inTable('nivaro_users')
    t.uuid('delegate_id').references('id').inTable('nivaro_users')
    t.datetime('delegate_expires_at')
    t.boolean('is_out_of_office').notNullable().defaultTo(false)
    t.string('totp_secret', 255)
    t.boolean('totp_enabled').notNullable().defaultTo(false)
    t.string('phone', 50)
    t.datetime('last_digest_at')
    t.boolean('is_redacted').notNullable().defaultTo(false)
    t.datetime('redacted_at')
  })

  await create(knex, 'nivaro_collections', (t) => {
    t.increments('id').primary()
    t.string('collection', 255).notNullable().unique()
    t.string('display_name', 255)
    t.string('singular', 255)
    t.string('plural', 255)
    t.string('icon', 100)
    t.text('note')
    t.string('color', 50)
    t.boolean('hidden').notNullable().defaultTo(false)
    t.boolean('singleton').notNullable().defaultTo(false)
    t.string('sort_field', 255)
    t.string('archive_field', 255)
    t.string('archive_value', 255)
    t.string('unarchive_value', 255)
    t.string('display_template', 500)
    t.string('group', 255)
    t.integer('sort')
    t.string('accountability', 50).notNullable().defaultTo('all')
    t.boolean('versioning').notNullable().defaultTo(false)
    t.datetime('created_at').notNullable().defaultTo(knex.fn.now())
    t.datetime('updated_at').notNullable().defaultTo(knex.fn.now())
    t.uuid('workspace').references('id').inTable('nivaro_workspaces')
    t.boolean('draft_publish_enabled').notNullable().defaultTo(false)
    t.boolean('is_virtual').notNullable().defaultTo(false)
    t.text('virtual_sql')
    t.boolean('item_locking_enabled').notNullable().defaultTo(true)
    t.boolean('addendums_enabled').notNullable().defaultTo(false)
  })

  await create(knex, 'nivaro_fields', (t) => {
    t.increments('id').primary()
    t.string('collection', 255).notNullable()
    t.string('field', 255).notNullable()
    t.string('type', 100).notNullable().defaultTo('string')
    t.string('db_column', 255)
    t.string('interface', 100)
    t.string('display', 100)
    t.text('display_options')
    t.text('options')
    t.string('note', 500)
    t.boolean('hidden').notNullable().defaultTo(false)
    t.boolean('readonly').notNullable().defaultTo(false)
    t.boolean('required').notNullable().defaultTo(false)
    t.integer('sort')
    t.string('group', 255)
    t.text('special')
    t.text('validation')
    t.string('validation_message', 500)
    t.datetime('created_at').notNullable().defaultTo(knex.fn.now())
    t.datetime('updated_at').notNullable().defaultTo(knex.fn.now())
    t.text('computed_formula')
    t.string('computed_type', 10)
    t.boolean('computed_store').notNullable().defaultTo(false)
    t.string('group_key', 100)
    t.text('visibility_rules')
    t.text('dependency_config')
    t.text('validation_rules')
    t.text('lock_condition')
    t.string('default_formula', 500)
    t.text('cross_record_defaults')
    t.text('remote_options_config')
    t.text('repeater_schema')
    t.boolean('is_translatable').notNullable().defaultTo(false)
    t.boolean('is_encrypted').notNullable().defaultTo(false)
    t.boolean('is_inheritable').notNullable().defaultTo(false)
    t.string('label', 255)
    t.unique(['collection', 'field'])
  })

  await create(knex, 'nivaro_policies', (t) => {
    t.increments('id').primary()
    t.uuid('role').notNullable().references('id').inTable('nivaro_roles').onDelete('CASCADE')
    t.string('collection', 255).notNullable()
    t.string('action', 50).notNullable()
    t.text('fields')
    t.text('permissions')
    t.text('validation')
    t.text('presets')
    t.datetime('created_at').notNullable().defaultTo(knex.fn.now())
    t.text('row_filter')
  })

  await create(knex, 'nivaro_tree_configs', (t) => {
    t.increments('id').primary()
    t.string('collection', 255).notNullable().unique()
    t.string('parent_field', 255).notNullable().defaultTo('parent_id')
    t.string('label_field', 255).notNullable().defaultTo('name')
    t.string('order_field', 255)
    t.datetime('created_at').defaultTo(knex.fn.now())
    t.boolean('maintain_path').notNullable().defaultTo(false)
  })

  await create(knex, 'nivaro_tree_permissions', (t) => {
    t.increments('id').primary()
    t.string('collection', 100).notNullable()
    t.string('node_id', 100).notNullable()
    t.uuid('role').notNullable().references('id').inTable('nivaro_roles')
    t.string('action', 20).notNullable().defaultTo('*')
    t.boolean('allow').notNullable().defaultTo(true)
    t.datetime('created_at').defaultTo(knex.fn.now())
    t.index(['collection', 'node_id'])
  })

  await create(knex, 'nivaro_workflow_bindings', (t) => {
    t.increments('id').primary()
    t.uuid('template').notNullable().references('id').inTable('nivaro_workflow_templates').onDelete('CASCADE')
    t.string('collection', 255).notNullable().unique()
    t.string('state_field', 255)
    t.boolean('auto_start').notNullable().defaultTo(false)
    t.string('auto_start_state', 36)
  })

  await create(knex, 'nivaro_workflow_transitions', (t) => {
    t.uuid('id').primary().defaultTo(knex.fn.uuid())
    t.uuid('template').notNullable().references('id').inTable('nivaro_workflow_templates').onDelete('CASCADE')
    t.uuid('from_state').references('id').inTable('nivaro_workflow_states')
    t.uuid('to_state').notNullable().references('id').inTable('nivaro_workflow_states')
    t.string('label', 255).notNullable()
    t.string('color', 50)
    t.text('required_roles')
    t.text('actions')
    t.integer('sort').notNullable().defaultTo(0)
    t.text('conditions')
    t.boolean('auto_trigger').notNullable().defaultTo(false)
    t.string('group_label', 255)
    t.text('condition_rules')
    t.index(['template'])
  })

  await create(knex, 'nivaro_workflow_instances', (t) => {
    t.uuid('id').primary().defaultTo(knex.fn.uuid())
    t.uuid('template').notNullable().references('id').inTable('nivaro_workflow_templates')
    t.string('collection', 255).notNullable()
    t.string('item', 255).notNullable()
    t.uuid('current_state').references('id').inTable('nivaro_workflow_states')
    t.datetime('started_at').notNullable().defaultTo(knex.fn.now())
    t.datetime('completed_at')
    t.index(['collection', 'item'])
  })

  await create(knex, 'nivaro_pipeline_owner_dimensions', (t) => {
    t.increments('id').primary()
    t.integer('binding').notNullable().references('id').inTable('nivaro_workflow_bindings').onDelete('CASCADE')
    t.string('field', 255).notNullable()
    t.string('label', 255).notNullable()
    t.integer('sort').notNullable().defaultTo(0)
    t.boolean('is_row_axis').notNullable().defaultTo(false)
    t.boolean('required').notNullable().defaultTo(false)
    t.index(['binding'])
  })

  await create(knex, 'nivaro_pipeline_owner_groups', (t) => {
    t.uuid('id').primary().defaultTo(knex.fn.uuid())
    t.uuid('template').notNullable().references('id').inTable('nivaro_workflow_templates').onDelete('CASCADE')
    t.uuid('state').notNullable().references('id').inTable('nivaro_workflow_states')
    t.string('name', 255)
    t.text('filters')
    t.integer('sort').notNullable().defaultTo(0)
    t.boolean('is_default').notNullable().defaultTo(false)
    t.integer('priority').notNullable().defaultTo(0)
    t.index(['state'])
    t.index(['template'])
  })

  // ── Tables that depend on nivaro_users ────────────────────────────────────

  await create(knex, 'nivaro_revisions', (t) => {
    t.increments('id').primary()
    t.integer('activity').references('id').inTable('nivaro_activity')
    t.string('collection', 255).notNullable()
    t.string('item', 255).notNullable()
    t.text('data').notNullable()
    t.text('delta')
    t.integer('parent').references('id').inTable('nivaro_revisions')
    t.index(['collection', 'item'])
  })

  await create(knex, 'nivaro_sessions', (t) => {
    t.string('id', 255).primary()
    t.uuid('user_id').references('id').inTable('nivaro_users').onDelete('CASCADE')
    t.text('data').notNullable()
    t.datetime('created_at').notNullable().defaultTo(knex.fn.now())
    t.datetime('expires_at').notNullable()
  })

  await create(knex, 'nivaro_notifications', (t) => {
    t.increments('id').primary()
    t.datetime('timestamp').notNullable().defaultTo(knex.fn.now())
    t.string('status', 50).notNullable().defaultTo('inbox')
    t.uuid('recipient').notNullable().references('id').inTable('nivaro_users').onDelete('CASCADE')
    t.uuid('sender')
    t.string('subject', 255).notNullable()
    t.text('message')
    t.string('collection', 255)
    t.string('item', 255)
    t.index(['recipient', 'status'])
  })

  await create(knex, 'nivaro_files', (t) => {
    t.uuid('id').primary().defaultTo(knex.fn.uuid())
    t.string('storage', 100).notNullable().defaultTo('local')
    t.string('filename_disk', 500)
    t.string('filename_download', 255).notNullable()
    t.string('title', 255)
    t.string('type', 255)
    t.uuid('folder').references('id').inTable('nivaro_file_folders').onDelete('SET NULL')
    t.uuid('uploaded_by').references('id').inTable('nivaro_users').onDelete('SET NULL')
    t.datetime('uploaded_on').notNullable().defaultTo(knex.fn.now())
    t.uuid('modified_by')
    t.datetime('modified_on')
    t.bigInteger('filesize')
    t.integer('width')
    t.integer('height')
    t.integer('duration')
    t.text('description')
    t.string('location', 500)
    t.text('tags')
    t.text('metadata')
    t.datetime('expires_at')
    t.string('storage_provider', 20).notNullable().defaultTo('local')
  })

  await create(knex, 'nivaro_flow_operations', (t) => {
    t.uuid('id').primary().defaultTo(knex.fn.uuid())
    t.uuid('flow').notNullable().references('id').inTable('nivaro_flows').onDelete('CASCADE')
    t.string('name', 255).notNullable()
    t.string('key', 100).notNullable()
    t.string('type', 100).notNullable()
    t.integer('position_x').notNullable().defaultTo(0)
    t.integer('position_y').notNullable().defaultTo(0)
    t.text('options')
    t.uuid('resolve').references('id').inTable('nivaro_flow_operations')
    t.uuid('reject').references('id').inTable('nivaro_flow_operations')
    t.datetime('created_at').notNullable().defaultTo(knex.fn.now())
    t.index(['flow'])
  })

  await create(knex, 'nivaro_flow_runs', (t) => {
    t.uuid('id').primary()
    t.uuid('flow').notNullable().references('id').inTable('nivaro_flows').onDelete('CASCADE')
    t.string('trigger', 50).notNullable()
    t.string('status', 50).notNullable().defaultTo('running')
    t.datetime('started_at').notNullable().defaultTo(knex.fn.now())
    t.datetime('completed_at')
    t.bigInteger('duration_ms')
    t.text('input')
    t.text('output')
    t.text('error_message')
    t.uuid('user').references('id').inTable('nivaro_users')
    t.index(['flow'])
    t.index(['status'])
  })

  await create(knex, 'nivaro_flow_versions', (t) => {
    t.increments('id').primary()
    t.uuid('flow').notNullable().references('id').inTable('nivaro_flows')
    t.integer('version').notNullable()
    t.text('definition').notNullable()
    t.uuid('created_by').notNullable().references('id').inTable('nivaro_users')
    t.datetime('created_at').defaultTo(knex.fn.now())
    t.unique(['flow', 'version'])
  })

  await create(knex, 'nivaro_comments', (t) => {
    t.uuid('id').primary()
    t.string('collection', 255).notNullable()
    t.string('item', 255).notNullable()
    t.uuid('user').notNullable().references('id').inTable('nivaro_users')
    t.text('text').notNullable()
    t.datetime('created_at').notNullable().defaultTo(knex.fn.now())
    t.datetime('updated_at').notNullable().defaultTo(knex.fn.now())
    t.index(['collection', 'item'])
  })

  await create(knex, 'nivaro_comment_mentions', (t) => {
    t.increments('id').primary()
    t.uuid('comment').notNullable().references('id').inTable('nivaro_comments').onDelete('CASCADE')
    t.uuid('user').notNullable().references('id').inTable('nivaro_users')
    t.index(['comment'])
    t.index(['user'])
  })

  await create(knex, 'nivaro_dashboards', (t) => {
    t.uuid('id').primary()
    t.string('name', 255).notNullable()
    t.uuid('user').references('id').inTable('nivaro_users')
    t.boolean('is_shared').notNullable().defaultTo(false)
    t.datetime('created_at').notNullable().defaultTo(knex.fn.now())
    t.datetime('updated_at').notNullable().defaultTo(knex.fn.now())
  })

  await create(knex, 'nivaro_dashboard_widgets', (t) => {
    t.uuid('id').primary()
    t.uuid('dashboard').notNullable().references('id').inTable('nivaro_dashboards')
    t.string('type', 50).notNullable()
    t.string('title', 255).notNullable()
    t.string('collection', 255)
    t.string('field', 255)
    t.text('filters')
    t.integer('col').notNullable().defaultTo(0)
    t.integer('row').notNullable().defaultTo(0)
    t.integer('width').notNullable().defaultTo(1)
    t.integer('height').notNullable().defaultTo(1)
    t.datetime('created_at').notNullable().defaultTo(knex.fn.now())
  })

  await create(knex, 'nivaro_collection_presets', (t) => {
    t.uuid('id').primary()
    t.string('collection', 255).notNullable()
    t.string('name', 255).notNullable()
    t.uuid('user_id').references('id').inTable('nivaro_users')
    t.text('columns').notNullable()
    t.boolean('is_default').notNullable().defaultTo(false)
    t.datetime('created_at').notNullable().defaultTo(knex.fn.now())
    t.index(['collection', 'user_id'])
  })

  await create(knex, 'nivaro_approval_chains', (t) => {
    t.increments('id').primary()
    t.string('name', 255).notNullable()
    t.string('collection', 100)
    t.uuid('workflow_template').references('id').inTable('nivaro_workflow_templates')
    t.string('state_key', 100)
    t.boolean('is_active').notNullable().defaultTo(true)
    t.datetime('created_at').defaultTo(knex.fn.now())
  })

  await create(knex, 'nivaro_approval_chain_steps', (t) => {
    t.increments('id').primary()
    t.integer('chain').notNullable().references('id').inTable('nivaro_approval_chains')
    t.integer('step_order').notNullable()
    t.uuid('approver').references('id').inTable('nivaro_users')
    t.uuid('approver_role').references('id').inTable('nivaro_roles')
    t.string('label', 255)
  })

  await create(knex, 'nivaro_approval_instances', (t) => {
    t.increments('id').primary()
    t.integer('chain').notNullable().references('id').inTable('nivaro_approval_chains')
    t.string('collection', 100).notNullable()
    t.string('item', 100).notNullable()
    t.integer('current_step').notNullable().defaultTo(0)
    t.string('status', 20).notNullable().defaultTo('pending')
    t.uuid('started_by').notNullable().references('id').inTable('nivaro_users')
    t.datetime('created_at').defaultTo(knex.fn.now())
  })

  await create(knex, 'nivaro_approval_decisions', (t) => {
    t.increments('id').primary()
    t.integer('instance').notNullable().references('id').inTable('nivaro_approval_instances')
    t.integer('step_order').notNullable()
    t.uuid('user').notNullable().references('id').inTable('nivaro_users')
    t.string('decision', 20).notNullable()
    t.text('comment')
    t.datetime('decided_at').defaultTo(knex.fn.now())
  })

  await create(knex, 'nivaro_addendums', (t) => {
    t.uuid('id').primary().defaultTo(knex.fn.uuid())
    t.string('parent_collection', 255).notNullable()
    t.string('parent_id', 255).notNullable()
    t.string('title', 500).notNullable()
    t.text('description')
    t.uuid('workflow_template_id').references('id').inTable('nivaro_workflow_templates')
    t.string('current_state', 255)
    t.text('fields_schema')
    t.text('data')
    t.float('cost_impact')
    t.integer('timeline_impact_days')
    t.string('status', 50).notNullable().defaultTo('draft')
    t.uuid('created_by').references('id').inTable('nivaro_users')
    t.datetime('created_at').defaultTo(knex.fn.now())
    t.datetime('updated_at').defaultTo(knex.fn.now())
  })

  await create(knex, 'nivaro_addendum_approvals', (t) => {
    t.increments('id').primary()
    t.string('parent_collection', 255).notNullable()
    t.string('parent_id', 255).notNullable()
    t.uuid('addendum_id').notNullable().references('id').inTable('nivaro_addendums')
    t.integer('order_number').notNullable()
    t.float('net_cost_impact')
    t.integer('net_timeline_impact_days')
    t.datetime('approved_at')
    t.uuid('approved_by').references('id').inTable('nivaro_users')
    t.text('notes')
    t.datetime('created_at').defaultTo(knex.fn.now())
  })

  await create(knex, 'nivaro_alert_definitions', (t) => {
    t.increments('id').primary()
    t.string('name', 255).notNullable()
    t.string('category', 100).notNullable().defaultTo('general')
    t.string('collection', 255).notNullable()
    t.string('field', 255).notNullable()
    t.string('operator', 50).notNullable()
    t.float('threshold').notNullable()
    t.string('unit', 50).notNullable().defaultTo('count')
    t.text('filters')
    t.integer('cooldown_minutes').notNullable().defaultTo(60)
    t.boolean('is_active').notNullable().defaultTo(true)
    t.uuid('created_by').references('id').inTable('nivaro_users')
    t.datetime('created_at').notNullable()
    t.datetime('updated_at').notNullable()
    t.string('detection_type', 20).notNullable().defaultTo('threshold')
    t.float('sensitivity')
  })

  await create(knex, 'nivaro_alert_log', (t) => {
    t.increments('id').primary()
    t.integer('alert_definition').notNullable().references('id').inTable('nivaro_alert_definitions')
    t.string('collection', 255).notNullable()
    t.string('item', 255).notNullable()
    t.string('field_value', 500)
    t.datetime('triggered_at').notNullable()
  })

  await create(knex, 'nivaro_alert_subscriptions', (t) => {
    t.increments('id').primary()
    t.integer('alert_definition').notNullable().references('id').inTable('nivaro_alert_definitions')
    t.uuid('user').notNullable().references('id').inTable('nivaro_users')
    t.boolean('notify_email').notNullable().defaultTo(true)
    t.boolean('notify_inapp').notNullable().defaultTo(true)
    t.unique(['alert_definition', 'user'])
  })

  await create(knex, 'nivaro_api_keys', (t) => {
    t.increments('id').primary()
    t.string('name', 255).notNullable()
    t.string('key_hash', 255).notNullable().unique()
    t.string('prefix', 20).notNullable()
    t.uuid('user').notNullable().references('id').inTable('nivaro_users')
    t.text('scopes').notNullable()
    t.datetime('expires_at')
    t.integer('rate_limit_per_minute')
    t.text('ip_allowlist')
    t.datetime('last_used_at')
    t.boolean('is_active').notNullable().defaultTo(true)
    t.datetime('created_at').defaultTo(knex.fn.now())
  })

  await create(knex, 'nivaro_at_risk_rules', (t) => {
    t.increments('id').primary()
    t.string('collection', 100).notNullable()
    t.string('name', 255).notNullable()
    t.text('conditions').notNullable()
    t.string('highlight_color', 20)
    t.boolean('is_active').notNullable().defaultTo(true)
    t.uuid('created_by').notNullable().references('id').inTable('nivaro_users')
    t.datetime('created_at').defaultTo(knex.fn.now())
  })

  await create(knex, 'nivaro_attribute_definitions', (t) => {
    t.increments('id').primary()
    t.string('collection', 255).notNullable()
    t.string('key', 255).notNullable()
    t.string('label', 255).notNullable()
    t.string('type', 50).notNullable().defaultTo('text')
    t.text('options')
    t.boolean('required').notNullable().defaultTo(false)
    t.integer('sort').notNullable().defaultTo(0)
    t.boolean('is_active').notNullable().defaultTo(true)
    t.uuid('created_by').references('id').inTable('nivaro_users')
    t.datetime('created_at').defaultTo(knex.fn.now())
    t.unique(['collection', 'key'])
  })

  await create(knex, 'nivaro_dq_runs', (t) => {
    t.increments('id').primary()
    t.string('collection', 100).notNullable()
    t.datetime('started_at').defaultTo(knex.fn.now())
    t.datetime('finished_at')
    t.integer('total_records')
    t.integer('failed_records')
    t.text('results')
    t.uuid('created_by').notNullable().references('id').inTable('nivaro_users')
  })

  await create(knex, 'nivaro_external_api_schemas', (t) => {
    t.increments('id').primary()
    t.integer('external_api_id').notNullable().references('id').inTable('nivaro_external_apis').onDelete('CASCADE')
    t.string('title', 255)
    t.string('spec_version', 50)
    t.text('raw_spec')
    t.integer('endpoint_count').defaultTo(0)
    t.datetime('imported_at').defaultTo(knex.fn.now())
    t.uuid('imported_by').references('id').inTable('nivaro_users').onDelete('SET NULL')
  })

  await create(knex, 'nivaro_erp_submissions', (t) => {
    t.increments('id').primary()
    t.string('collection', 100).notNullable()
    t.string('item', 100).notNullable()
    t.integer('external_api').notNullable().references('id').inTable('nivaro_external_apis')
    t.string('external_ref', 255)
    t.string('status', 20).notNullable().defaultTo('submitted')
    t.integer('attempts').notNullable().defaultTo(0)
    t.text('last_error')
    t.text('payload')
    t.datetime('created_at').defaultTo(knex.fn.now())
    t.datetime('updated_at').defaultTo(knex.fn.now())
  })

  await create(knex, 'nivaro_field_rules', (t) => {
    t.increments('id').primary()
    t.string('collection', 255).notNullable()
    t.string('trigger_field', 255).notNullable()
    t.string('trigger_op', 50).notNullable().defaultTo('eq')
    t.text('trigger_value')
    t.string('target_field', 255).notNullable()
    t.string('target_type', 50).notNullable().defaultTo('set')
    t.text('target_value')
    t.integer('sort').notNullable().defaultTo(0)
    t.boolean('is_active').notNullable().defaultTo(true)
    t.uuid('created_by').references('id').inTable('nivaro_users')
    t.datetime('created_at').defaultTo(knex.fn.now())
  })

  await create(knex, 'nivaro_field_watches', (t) => {
    t.increments('id').primary()
    t.string('name', 255).notNullable()
    t.string('collection', 255).notNullable()
    t.string('field', 255).notNullable()
    t.boolean('is_active').notNullable().defaultTo(true)
    t.uuid('created_by').references('id').inTable('nivaro_users')
    t.datetime('created_at').notNullable()
    t.datetime('updated_at').notNullable()
  })

  await create(knex, 'nivaro_field_watch_subscribers', (t) => {
    t.increments('id').primary()
    t.integer('watch').notNullable().references('id').inTable('nivaro_field_watches')
    t.uuid('user').notNullable().references('id').inTable('nivaro_users')
    t.unique(['watch', 'user'])
  })

  await create(knex, 'nivaro_field_translations', (t) => {
    t.increments('id').primary()
    t.string('collection', 255).notNullable()
    t.string('item_id', 255).notNullable()
    t.string('field', 255).notNullable()
    t.string('locale', 20).notNullable()
    t.text('value')
    t.datetime('updated_at').defaultTo(knex.fn.now())
    t.unique(['collection', 'item_id', 'field', 'locale'])
  })

  await create(knex, 'nivaro_hierarchy_configs', (t) => {
    t.increments('id').primary()
    t.string('name', 255).notNullable()
    t.text('description')
    t.text('levels').notNullable().defaultTo('[]')
    t.datetime('created_at').defaultTo(knex.fn.now())
    t.uuid('created_by').references('id').inTable('nivaro_users')
  })

  await create(knex, 'nivaro_import_jobs', (t) => {
    t.uuid('id').primary()
    t.string('collection', 255).notNullable()
    t.string('file_name', 500).notNullable()
    t.text('csv_data').notNullable()
    t.text('column_map')
    t.string('duplicate_strategy', 50).notNullable().defaultTo('skip')
    t.string('id_field', 255)
    t.string('status', 50).notNullable().defaultTo('pending')
    t.integer('total_rows')
    t.integer('processed_rows').defaultTo(0)
    t.integer('created_rows').defaultTo(0)
    t.integer('updated_rows').defaultTo(0)
    t.integer('skipped_rows').defaultTo(0)
    t.integer('error_rows').defaultTo(0)
    t.text('errors')
    t.uuid('created_by').references('id').inTable('nivaro_users')
    t.datetime('created_at').notNullable()
    t.datetime('started_at')
    t.datetime('completed_at')
  })

  await create(knex, 'nivaro_issues', (t) => {
    t.increments('id').primary()
    t.string('collection', 100)
    t.string('item', 100)
    t.string('title', 500).notNullable()
    t.string('severity', 20).notNullable().defaultTo('medium')
    t.string('status', 20).notNullable().defaultTo('open')
    t.uuid('assigned_to').references('id').inTable('nivaro_users')
    t.uuid('raised_by').notNullable().references('id').inTable('nivaro_users')
    t.text('resolution_notes')
    t.datetime('created_at').defaultTo(knex.fn.now())
    t.datetime('updated_at').defaultTo(knex.fn.now())
  })

  await create(knex, 'nivaro_item_locks', (t) => {
    t.increments('id').primary()
    t.string('collection', 100).notNullable()
    t.string('item', 100).notNullable()
    t.uuid('user').notNullable().references('id').inTable('nivaro_users')
    t.datetime('locked_at').defaultTo(knex.fn.now())
    t.datetime('expires_at').notNullable()
    t.unique(['collection', 'item'])
  })

  await create(knex, 'nivaro_notification_subscriptions', (t) => {
    t.increments('id').primary()
    t.uuid('user').notNullable().references('id').inTable('nivaro_users')
    t.string('collection', 255).notNullable()
    t.string('event_type', 50).notNullable()
    t.string('filter_field', 255)
    t.string('filter_value', 500)
    t.string('label', 255)
    t.boolean('is_active').notNullable().defaultTo(true)
    t.datetime('created_at').notNullable()
    t.string('digest_frequency', 10).notNullable().defaultTo('instant')
  })

  await create(knex, 'nivaro_pages', (t) => {
    t.increments('id').primary()
    t.string('name', 255).notNullable()
    t.string('slug', 100).notNullable().unique()
    t.string('icon', 50)
    t.text('layout').notNullable()
    t.boolean('is_shared').notNullable().defaultTo(true)
    t.uuid('role').references('id').inTable('nivaro_roles')
    t.integer('sort').notNullable().defaultTo(0)
    t.uuid('created_by').notNullable().references('id').inTable('nivaro_users')
    t.datetime('created_at').defaultTo(knex.fn.now())
    t.datetime('updated_at').defaultTo(knex.fn.now())
  })

  await create(knex, 'nivaro_pdf_templates', (t) => {
    t.increments('id').primary()
    t.string('name', 255).notNullable()
    t.string('collection', 100)
    t.text('template').notNullable()
    t.uuid('created_by').notNullable().references('id').inTable('nivaro_users')
    t.datetime('created_at').defaultTo(knex.fn.now())
    t.datetime('updated_at').defaultTo(knex.fn.now())
  })

  await create(knex, 'nivaro_persisted_queries', (t) => {
    t.increments('id').primary()
    t.string('hash', 64).notNullable().unique()
    t.string('name', 255).notNullable()
    t.text('query').notNullable()
    t.uuid('created_by').notNullable().references('id').inTable('nivaro_users')
    t.datetime('created_at').defaultTo(knex.fn.now())
  })

  await create(knex, 'nivaro_pipeline_instance_owners', (t) => {
    t.increments('id').primary()
    t.uuid('instance').notNullable().references('id').inTable('nivaro_workflow_instances').onDelete('CASCADE')
    t.uuid('state').references('id').inTable('nivaro_workflow_states')
    t.uuid('user').notNullable().references('id').inTable('nivaro_users')
    t.uuid('added_by').references('id').inTable('nivaro_users')
    t.datetime('added_at').notNullable().defaultTo(knex.fn.now())
    t.index(['instance'])
  })

  await create(knex, 'nivaro_pipeline_owner_group_users', (t) => {
    t.increments('id').primary()
    t.uuid('group').notNullable().references('id').inTable('nivaro_pipeline_owner_groups').onDelete('CASCADE')
    t.uuid('user').notNullable().references('id').inTable('nivaro_users')
    t.index(['group'])
    t.unique(['group', 'user'])
  })

  await create(knex, 'nivaro_record_templates', (t) => {
    t.increments('id').primary()
    t.string('collection', 255).notNullable()
    t.string('name', 255).notNullable()
    t.string('description', 500)
    t.text('data').notNullable()
    t.uuid('role_id').references('id').inTable('nivaro_roles')
    t.boolean('is_shared').notNullable().defaultTo(true)
    t.uuid('created_by').references('id').inTable('nivaro_users')
    t.datetime('created_at').defaultTo(knex.fn.now())
    t.datetime('updated_at').defaultTo(knex.fn.now())
  })

  await create(knex, 'nivaro_retention_policies', (t) => {
    t.increments('id').primary()
    t.string('name', 255).notNullable()
    t.integer('inactivity_threshold_months').notNullable().defaultTo(36)
    t.string('action', 32).notNullable().defaultTo('redact')
    t.text('redact_fields')
    t.string('redact_value_template', 500).defaultTo('Redacted_{{id}}')
    t.text('exclusion_emails')
    t.text('exclusion_roles')
    t.string('cron_schedule', 100)
    t.boolean('is_active').notNullable().defaultTo(true)
    t.boolean('dry_run_mode').notNullable().defaultTo(false)
    t.datetime('last_run_at')
    t.integer('last_run_affected_count')
    t.uuid('created_by').references('id').inTable('nivaro_users').onDelete('SET NULL')
    t.datetime('created_at').notNullable().defaultTo(knex.fn.now())
    t.datetime('updated_at').notNullable().defaultTo(knex.fn.now())
  })

  await create(knex, 'nivaro_retention_runs', (t) => {
    t.increments('id').primary()
    t.integer('policy_id').notNullable().references('id').inTable('nivaro_retention_policies').onDelete('CASCADE')
    t.datetime('started_at').notNullable()
    t.datetime('finished_at')
    t.integer('affected_count').notNullable().defaultTo(0)
    t.boolean('dry_run').notNullable().defaultTo(false)
    t.text('errors')
    t.text('affected_ids')
    t.uuid('triggered_by').references('id').inTable('nivaro_users').onDelete('SET NULL')
  })

  await create(knex, 'nivaro_saved_views', (t) => {
    t.increments('id').primary()
    t.string('collection', 100).notNullable()
    t.string('name', 255).notNullable()
    t.text('filters').notNullable()
    t.text('sort')
    t.text('columns')
    t.uuid('user').notNullable().references('id').inTable('nivaro_users')
    t.boolean('is_shared').notNullable().defaultTo(false)
    t.uuid('role').references('id').inTable('nivaro_roles')
    t.datetime('created_at').defaultTo(knex.fn.now())
  })

  await create(knex, 'nivaro_scheduled_changes', (t) => {
    t.uuid('id').primary().defaultTo(knex.fn.uuid())
    t.string('collection', 255).notNullable()
    t.string('item_id', 255).notNullable()
    t.string('change_type', 50).notNullable().defaultTo('field_update')
    t.text('changes').notNullable()
    t.datetime('scheduled_at').notNullable()
    t.string('status', 50).notNullable().defaultTo('pending')
    t.datetime('executed_at')
    t.string('error_message', 500)
    t.string('inngest_event_id', 500)
    t.uuid('created_by').references('id').inTable('nivaro_users')
    t.datetime('created_at').defaultTo(knex.fn.now())
  })

  await create(knex, 'nivaro_sla_rules', (t) => {
    t.increments('id').primary()
    t.uuid('workflow_template').notNullable().references('id').inTable('nivaro_workflow_templates')
    t.string('state_key', 255).notNullable()
    t.string('name', 255).notNullable()
    t.integer('duration_hours').notNullable()
    t.integer('warning_threshold_pct').notNullable().defaultTo(80)
    t.boolean('business_hours_only').notNullable().defaultTo(false)
    t.boolean('notify_on_warning').notNullable().defaultTo(true)
    t.boolean('notify_on_breach').notNullable().defaultTo(true)
    t.uuid('escalation_user').references('id').inTable('nivaro_users')
    t.boolean('is_active').notNullable().defaultTo(true)
    t.datetime('created_at').notNullable()
    t.datetime('updated_at').notNullable()
  })

  await create(knex, 'nivaro_sub_rows', (t) => {
    t.increments('id').primary()
    t.string('parent_collection', 255).notNullable()
    t.string('parent_id', 255).notNullable()
    t.string('sub_row_field', 255).notNullable()
    t.integer('sort').notNullable().defaultTo(0)
    t.text('data').notNullable()
    t.datetime('created_at').defaultTo(knex.fn.now())
    t.datetime('updated_at').defaultTo(knex.fn.now())
  })

  await create(knex, 'nivaro_sub_row_templates', (t) => {
    t.increments('id').primary()
    t.string('collection', 255).notNullable()
    t.string('field', 255).notNullable()
    t.string('name', 255).notNullable()
    t.text('items').notNullable()
    t.uuid('created_by').references('id').inTable('nivaro_users')
    t.datetime('created_at').defaultTo(knex.fn.now())
  })

  await create(knex, 'nivaro_submission_forms', (t) => {
    t.uuid('id').primary()
    t.string('name', 255).notNullable()
    t.string('collection', 255).notNullable()
    t.text('fields').notNullable()
    t.string('token', 64).notNullable().unique()
    t.string('password_hash', 500)
    t.datetime('expires_at')
    t.integer('rate_limit_per_hour').notNullable().defaultTo(60)
    t.boolean('is_active').notNullable().defaultTo(true)
    t.text('success_message')
    t.uuid('created_by').references('id').inTable('nivaro_users')
    t.datetime('created_at').notNullable()
    t.datetime('updated_at').notNullable()
    t.text('form_config')
  })

  await create(knex, 'nivaro_submissions', (t) => {
    t.uuid('id').primary()
    t.uuid('form').notNullable().references('id').inTable('nivaro_submission_forms')
    t.text('data').notNullable()
    t.string('ip', 64)
    t.datetime('created_at').notNullable()
  })

  await create(knex, 'nivaro_sync_jobs', (t) => {
    t.increments('id').primary()
    t.string('name', 255).notNullable()
    t.string('direction', 10).notNullable()
    t.integer('external_api').notNullable().references('id').inTable('nivaro_external_apis')
    t.string('collection', 100).notNullable()
    t.string('endpoint_path', 500).notNullable()
    t.text('field_mapping').notNullable()
    t.string('conflict_strategy', 20).notNullable().defaultTo('newest-wins')
    t.string('schedule', 100)
    t.string('id_field', 100).notNullable().defaultTo('id')
    t.string('external_id_field', 100)
    t.boolean('is_active').notNullable().defaultTo(true)
    t.datetime('last_run_at')
    t.string('last_run_status', 20)
    t.text('last_run_stats')
    t.uuid('created_by').notNullable().references('id').inTable('nivaro_users')
    t.datetime('created_at').defaultTo(knex.fn.now())
    t.datetime('updated_at').defaultTo(knex.fn.now())
  })

  await create(knex, 'nivaro_tasks', (t) => {
    t.increments('id').primary()
    t.string('collection', 100).notNullable()
    t.string('item', 100).notNullable()
    t.string('title', 500).notNullable()
    t.text('description')
    t.uuid('assignee').notNullable().references('id').inTable('nivaro_users')
    t.datetime('due_date')
    t.string('status', 20).notNullable().defaultTo('open')
    t.uuid('created_by').notNullable().references('id').inTable('nivaro_users')
    t.datetime('completed_at')
    t.datetime('created_at').defaultTo(knex.fn.now())
    t.datetime('updated_at').defaultTo(knex.fn.now())
  })

  await create(knex, 'nivaro_webhook_deliveries', (t) => {
    t.increments('id').primary()
    t.integer('webhook').notNullable().references('id').inTable('nivaro_webhooks')
    t.string('event', 100).notNullable()
    t.integer('status_code')
    t.text('request_body')
    t.text('response_body')
    t.integer('latency_ms')
    t.boolean('success').notNullable().defaultTo(false)
    t.integer('attempt').notNullable().defaultTo(1)
    t.datetime('created_at').defaultTo(knex.fn.now())
  })

  await create(knex, 'nivaro_widget_feeds', (t) => {
    t.increments('id').primary()
    t.string('name', 255).notNullable()
    t.string('token', 64).notNullable().unique()
    t.string('collection', 100).notNullable()
    t.text('fields').notNullable()
    t.text('filters')
    t.integer('limit_count').notNullable().defaultTo(20)
    t.string('sort', 100)
    t.boolean('is_active').notNullable().defaultTo(true)
    t.uuid('created_by').notNullable().references('id').inTable('nivaro_users')
    t.datetime('created_at').defaultTo(knex.fn.now())
  })

  await create(knex, 'nivaro_workflow_history', (t) => {
    t.increments('id').primary()
    t.uuid('instance').notNullable().references('id').inTable('nivaro_workflow_instances').onDelete('CASCADE')
    t.uuid('transition').references('id').inTable('nivaro_workflow_transitions')
    t.uuid('from_state').references('id').inTable('nivaro_workflow_states')
    t.uuid('to_state').notNullable().references('id').inTable('nivaro_workflow_states')
    t.uuid('user').references('id').inTable('nivaro_users')
    t.text('comment')
    t.datetime('timestamp').notNullable().defaultTo(knex.fn.now())
    t.index(['instance'])
  })

  await create(knex, 'nivaro_workspace_templates', (t) => {
    t.increments('id').primary()
    t.string('name', 255).notNullable()
    t.text('description')
    t.uuid('source_workspace')
    t.text('data').notNullable()
    t.uuid('created_by').notNullable().references('id').inTable('nivaro_users')
    t.datetime('created_at').defaultTo(knex.fn.now())
  })

  await create(knex, 'nivaro_usage_counters', (t) => {
    t.increments('id').primary()
    t.uuid('workspace').notNullable()
    t.string('metric', 50).notNullable()
    t.string('period', 20).notNullable()
    t.bigInteger('value').notNullable().defaultTo(0)
    t.unique(['workspace', 'metric', 'period'])
  })

  // ── Insert default settings row ───────────────────────────────────────────
  const hasSettings = await knex('nivaro_settings').count('* as c').first()
  if (!hasSettings || Number((hasSettings as any).c) === 0) {
    await knex('nivaro_settings').insert({ updated_at: new Date() })
  }
}

export async function down(knex: Knex): Promise<void> {
  // Drop in reverse dependency order
  const tables = [
    'nivaro_workspace_templates', 'nivaro_workflow_history', 'nivaro_widget_feeds',
    'nivaro_webhook_deliveries', 'nivaro_tasks', 'nivaro_sync_jobs', 'nivaro_submissions',
    'nivaro_submission_forms', 'nivaro_sub_row_templates', 'nivaro_sub_rows',
    'nivaro_sla_rules', 'nivaro_scheduled_changes', 'nivaro_saved_views',
    'nivaro_retention_runs', 'nivaro_retention_policies', 'nivaro_record_templates',
    'nivaro_pipeline_owner_group_users', 'nivaro_pipeline_instance_owners',
    'nivaro_persisted_queries', 'nivaro_pdf_templates', 'nivaro_pages',
    'nivaro_notification_subscriptions', 'nivaro_item_locks', 'nivaro_issues',
    'nivaro_import_jobs', 'nivaro_hierarchy_configs', 'nivaro_field_watch_subscribers',
    'nivaro_field_watches', 'nivaro_field_translations', 'nivaro_field_rules',
    'nivaro_erp_submissions', 'nivaro_external_api_schemas', 'nivaro_dq_runs',
    'nivaro_attribute_definitions', 'nivaro_at_risk_rules', 'nivaro_api_keys',
    'nivaro_approval_decisions', 'nivaro_approval_instances', 'nivaro_approval_chain_steps',
    'nivaro_approval_chains', 'nivaro_addendum_approvals', 'nivaro_addendums',
    'nivaro_alert_subscriptions', 'nivaro_alert_log', 'nivaro_alert_definitions',
    'nivaro_collection_presets', 'nivaro_dashboard_widgets', 'nivaro_dashboards',
    'nivaro_comment_mentions', 'nivaro_comments', 'nivaro_flow_versions',
    'nivaro_flow_runs', 'nivaro_flow_operations', 'nivaro_files',
    'nivaro_sessions', 'nivaro_revisions', 'nivaro_notifications',
    'nivaro_pipeline_owner_group_users', 'nivaro_pipeline_owner_groups',
    'nivaro_pipeline_owner_dimensions', 'nivaro_workflow_instances',
    'nivaro_workflow_history', 'nivaro_workflow_transitions', 'nivaro_workflow_bindings',
    'nivaro_workflow_states', 'nivaro_tree_permissions', 'nivaro_tree_configs',
    'nivaro_policies', 'nivaro_fields', 'nivaro_collections', 'nivaro_users',
    'nivaro_roles', 'nivaro_workspaces', 'nivaro_workflow_templates',
    'nivaro_flows', 'nivaro_file_folders', 'nivaro_webhooks', 'nivaro_settings',
    'nivaro_sequences', 'nivaro_relations', 'nivaro_page_views',
    'nivaro_external_api_endpoints', 'nivaro_external_api_logs', 'nivaro_external_apis',
    'nivaro_erp_submissions', 'nivaro_embeddings', 'nivaro_dq_rules',
    'nivaro_custom_queries', 'nivaro_collection_layouts', 'nivaro_blackout_dates',
    'nivaro_attribute_values', 'nivaro_api_logs', 'nivaro_activity',
    'nivaro_ai_collection_settings', 'nivaro_layout_field_assignments',
    'nivaro_field_groups', 'nivaro_usage_counters',
  ]
  for (const table of tables) {
    await knex.schema.dropTableIfExists(table)
  }
}
