import type { Knex } from 'knex'

export async function up(knex: Knex): Promise<void> {
  await knex.schema.createTable('nivaro_tasks', (t) => {
    t.increments('id')
    t.string('collection', 100).notNullable()
    t.string('item', 100).notNullable()
    t.string('title', 500).notNullable()
    t.specificType('description', 'nvarchar(max)').nullable()
    t.uuid('assignee').notNullable()
    t.foreign('assignee')
      .references('id')
      .inTable('nivaro_users')
      .onDelete('NO ACTION')
      .onUpdate('NO ACTION')
    t.datetime('due_date').nullable()
    t.string('status', 20).notNullable().defaultTo('open')
    t.uuid('created_by').notNullable()
    t.foreign('created_by')
      .references('id')
      .inTable('nivaro_users')
      .onDelete('NO ACTION')
      .onUpdate('NO ACTION')
    t.datetime('completed_at').nullable()
    t.datetime('created_at').defaultTo(knex.fn.now())
    t.datetime('updated_at').defaultTo(knex.fn.now())
  })

  await knex.schema.createTable('nivaro_approval_chains', (t) => {
    t.increments('id')
    t.string('name', 255).notNullable()
    t.string('collection', 100).nullable()
    t.uuid('workflow_template').nullable() // nivaro_workflow_templates uses a uniqueidentifier PK
    t.foreign('workflow_template')
      .references('id')
      .inTable('nivaro_workflow_templates')
      .onDelete('NO ACTION')
      .onUpdate('NO ACTION')
    t.string('state_key', 100).nullable()
    t.boolean('is_active').notNullable().defaultTo(true)
    t.datetime('created_at').defaultTo(knex.fn.now())
  })

  await knex.schema.createTable('nivaro_approval_chain_steps', (t) => {
    t.increments('id')
    t.integer('chain').notNullable()
    t.foreign('chain')
      .references('id')
      .inTable('nivaro_approval_chains')
      .onDelete('NO ACTION')
      .onUpdate('NO ACTION')
    t.integer('step_order').notNullable()
    t.uuid('approver').nullable()
    t.foreign('approver')
      .references('id')
      .inTable('nivaro_users')
      .onDelete('NO ACTION')
      .onUpdate('NO ACTION')
    t.uuid('approver_role').nullable() // nivaro_roles uses a uniqueidentifier PK
    t.foreign('approver_role')
      .references('id')
      .inTable('nivaro_roles')
      .onDelete('NO ACTION')
      .onUpdate('NO ACTION')
    t.string('label', 255).nullable()
  })

  await knex.schema.createTable('nivaro_approval_instances', (t) => {
    t.increments('id')
    t.integer('chain').notNullable()
    t.foreign('chain')
      .references('id')
      .inTable('nivaro_approval_chains')
      .onDelete('NO ACTION')
      .onUpdate('NO ACTION')
    t.string('collection', 100).notNullable()
    t.string('item', 100).notNullable()
    t.integer('current_step').notNullable().defaultTo(0)
    t.string('status', 20).notNullable().defaultTo('pending')
    t.uuid('started_by').notNullable()
    t.foreign('started_by')
      .references('id')
      .inTable('nivaro_users')
      .onDelete('NO ACTION')
      .onUpdate('NO ACTION')
    t.datetime('created_at').defaultTo(knex.fn.now())
  })

  await knex.schema.createTable('nivaro_approval_decisions', (t) => {
    t.increments('id')
    t.integer('instance').notNullable()
    t.foreign('instance')
      .references('id')
      .inTable('nivaro_approval_instances')
      .onDelete('NO ACTION')
      .onUpdate('NO ACTION')
    t.integer('step_order').notNullable()
    t.uuid('user').notNullable()
    t.foreign('user')
      .references('id')
      .inTable('nivaro_users')
      .onDelete('NO ACTION')
      .onUpdate('NO ACTION')
    t.string('decision', 20).notNullable()
    t.specificType('comment', 'nvarchar(max)').nullable()
    t.datetime('decided_at').defaultTo(knex.fn.now())
  })

  await knex.schema.createTable('nivaro_item_locks', (t) => {
    t.increments('id')
    t.string('collection', 100).notNullable()
    t.string('item', 100).notNullable()
    t.uuid('user').notNullable()
    t.foreign('user')
      .references('id')
      .inTable('nivaro_users')
      .onDelete('NO ACTION')
      .onUpdate('NO ACTION')
    t.datetime('locked_at').defaultTo(knex.fn.now())
    t.datetime('expires_at').notNullable()
  })
  await knex.raw(
    'ALTER TABLE nivaro_item_locks ADD CONSTRAINT uq_nivaro_item_locks UNIQUE (collection, item)'
  )
}

export async function down(knex: Knex): Promise<void> {
  await knex.schema.dropTableIfExists('nivaro_item_locks')
  await knex.schema.dropTableIfExists('nivaro_approval_decisions')
  await knex.schema.dropTableIfExists('nivaro_approval_instances')
  await knex.schema.dropTableIfExists('nivaro_approval_chain_steps')
  await knex.schema.dropTableIfExists('nivaro_approval_chains')
  await knex.schema.dropTableIfExists('nivaro_tasks')
}
